/** Final-byte CPU skin audit, independent from the exporter. Browser art review remains required. */
import assert from 'node:assert/strict';
import {NodeIO} from '@gltf-transform/core';
import {ALL_EXTENSIONS} from '@gltf-transform/extensions';
import {prune} from '@gltf-transform/functions';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import * as T from 'three';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const out='test-results/wilderness-creatures/ordinary',catalog=JSON.parse(await readFile(`${out}/catalog.json`,'utf8')),io=new NodeIO().registerExtensions(ALL_EXTENSIONS),report=[];
const expected=['Idle','Walk','Run','Attack','Hit','HitLeft','HitRight','Death'];
const median=a=>a.length?[...a].sort((a,b)=>a-b)[Math.floor(a.length/2)]:null;
const solePatterns={cinderback_crag:[/^FrontFootL$/,/^FrontFoot2R$/,/^MidFrontFootL$/,/^MidFrontFootR$/,/^MidBackFootL$/,/^MidBackFootR$/,/^BackFootL$/,/^BackFootR$/],rift_carapace:[/^FrontFootL$/,/^FrontFoot2R$/,/^MidFrontFootL$/,/^MidFrontFootR$/,/^MidBackFootL$/,/^MidBackFootR$/,/^BackFootL$/,/^BackFootR$/],furnace_grazer:[/earth_.*_(foot|toe|heel).*_L/,/earth_.*_(foot|toe|heel).*_R/],basalt_maw:[/beetle_25_/,/beetle_29_/],voidstone_colossus:[/^foot_l$/,/^foot_r$/]};
for(const asset of catalog.assets){
 const id=asset.id.replace('creature_',''),bytes=await readFile(`${out}/${catalog.files[asset.id]}`);assert.equal(createHash('sha256').update(bytes).digest('hex'),asset.sha256);const doc=await io.readBinary(bytes),r=doc.getRoot();
 for(const m of r.listMaterials()){m.setBaseColorTexture(null).setNormalTexture(null).setMetallicRoughnessTexture(null).setEmissiveTexture(null).setOcclusionTexture(null);}await doc.transform(prune());const bare=await io.writeBinary(doc),gltf=await new GLTFLoader().parseAsync(bare.buffer.slice(bare.byteOffset,bare.byteOffset+bare.byteLength),''),scene=gltf.scene,mixer=new T.AnimationMixer(scene);
 assert.deepEqual(gltf.animations.map(a=>a.name).sort(),expected.slice().sort());
 const row={id,sha256:asset.sha256,clips:{},gait:{},activeHorizontalRadiusM:0,allClipsHorizontalRadiusM:0,activeVertexRadiusM:0,allClipsVertexRadiusM:0};
 const patches=(solePatterns[id]??[]).map(pattern=>{const candidates=[];scene.traverse(mesh=>{if(!mesh.isMesh)return;const p=mesh.geometry.attributes.position;if(mesh.isSkinnedMesh){const si=mesh.geometry.attributes.skinIndex,sw=mesh.geometry.attributes.skinWeight,bones=new Set(mesh.skeleton.bones.flatMap((b,i)=>pattern.test(b.name)?[i]:[]));for(let i=0;i<p.count;i++){let w=0;for(let k=0;k<4;k++)if(bones.has(si.getComponent(i,k)))w+=sw.getComponent(i,k);if(w>.5)candidates.push({mesh,index:i});}}else if(pattern.test(mesh.parent.name)){for(let i=0;i<p.count;i++)candidates.push({mesh,index:i});}});assert(candidates.length,`${id} no sole vertices for ${pattern}`);return candidates;});
 for(const clip of gltf.animations){mixer.stopAllAction();const action=mixer.clipAction(clip).setLoop(T.LoopOnce,1);action.clampWhenFinished=true;action.play();const locomotion=['Walk','Run'].includes(clip.name),count=Math.max(locomotion?180:120,Math.ceil(clip.duration*(process.argv.includes('--120hz')?120:60))),union=new T.Box3(),traces=patches.map(()=>[]);let minFloor=Infinity,maxFloor=-Infinity,radius=0,vertexRadius=0;
  for(let i=0;i<count;i++){mixer.setTime(clip.duration*i/(count-1));scene.updateMatrixWorld(true);const b=new T.Box3().setFromObject(scene,true);assert([...b.min,...b.max].every(Number.isFinite),`${id} nonfinite ${clip.name}`);union.union(b);minFloor=Math.min(minFloor,b.min.y);maxFloor=Math.max(maxFloor,b.min.y);const rr=Math.hypot(Math.max(Math.abs(b.min.x),Math.abs(b.max.x)),Math.max(Math.abs(b.min.z),Math.abs(b.max.z)));radius=Math.max(radius,rr);
   const q=new T.Vector3();scene.traverse(mesh=>{if(!mesh.isMesh)return;for(let k=0;k<mesh.geometry.attributes.position.count;k++){mesh.getVertexPosition(k,q).applyMatrix4(mesh.matrixWorld);vertexRadius=Math.max(vertexRadius,Math.hypot(q.x,q.z));}});
   if(locomotion)patches.forEach((patch,j)=>traces[j].push(patch.map(({mesh,index})=>mesh.getVertexPosition(index,new T.Vector3()).applyMatrix4(mesh.matrixWorld))));
  }
  row.clips[clip.name]={duration:clip.duration,samples:count,minFloor,maxFloor,horizontalRadiusM:radius,vertexRadiusM:vertexRadius,bounds:{min:union.min.toArray(),max:union.max.toArray()}};row.allClipsHorizontalRadiusM=Math.max(row.allClipsHorizontalRadiusM,radius);row.allClipsVertexRadiusM=Math.max(row.allClipsVertexRadiusM,vertexRadius);if(clip.name!=='Death'){row.activeHorizontalRadiusM=Math.max(row.activeHorizontalRadiusM,radius);row.activeVertexRadiusM=Math.max(row.activeVertexRadiusM,vertexRadius);}
  assert(minFloor>-.04,`${id} ${clip.name} below ground ${minFloor}`);assert(maxFloor<(id==='gloam_wraith'&&clip.name!=='Death'?.145:.07),`${id} ${clip.name} ungrounded ${maxFloor}`);
  if(locomotion&&patches.length){const speeds=[],contacts=[];for(const [j,trace]of traces.entries()){const stance=[];for(let i=1;i<trace.length-1;i++){const min=Math.min(...trace[i].map(v=>v.y));if(min>.045){stance.push(null);continue;}const velocities=trace[i].flatMap((v,k)=>v.y<min+.015?[(trace[i-1][k].z-trace[i+1][k].z)/(2*clip.duration/(count-1))]:[]),speed=median(velocities);stance.push(speed>.025?speed:null);}const runs=[];let run=[];for(const v of stance){if(v!==null)run.push(v);else if(run.length){runs.push(run);run=[];}}if(run.length)runs.push(run);if(runs.length>1&&stance[0]!==null&&stance.at(-1)!==null)runs[0]=[...runs.pop(),...runs[0]];runs.sort((a,b)=>b.length-a.length);const main=runs[0]??[],trim=Math.floor(main.length*.15),core=main.slice(trim,main.length-trim);speeds.push(...core);contacts.push({side:j,vertices:patches[j].length,stanceSamples:stance.filter(v=>v!==null).length,medianMps:median(core)});}row.gait[clip.name]={impliedMps:median(speeds),contacts};}
 }
 report.push(row);console.log(JSON.stringify({id,activeRadius:row.activeHorizontalRadiusM,allRadius:row.allClipsHorizontalRadiusM,gait:Object.fromEntries(Object.entries(row.gait).map(([k,v])=>[k,v.impliedMps]))}));
 if(process.argv.includes('--apply')){if(row.gait.Walk?.impliedMps>0)asset.impliedWalkMps=row.gait.Walk.impliedMps;if(row.gait.Run?.impliedMps>0)asset.impliedRunMps=row.gait.Run.impliedMps;asset.metadata.wildernessAnatomy.cpuAudit=row;asset.metadata.gaitMeasurement={source:'assets/art/wilderness-creatures/ordinary/geometry-and-gait-audit.json',status:id==='gloam_wraith'?'authored-levitation':'measured-weighted-sole',visualContactAccepted:false};}
}
await writeFile(`${out}/cpu-audit.json`,JSON.stringify(report,null,2)+'\n');if(process.argv.includes('--apply')){await writeFile(`${out}/catalog.json`,JSON.stringify(catalog,null,2)+'\n');await writeFile('assets/art/wilderness-creatures/ordinary/geometry-and-gait-audit.json',JSON.stringify(report,null,2)+'\n');}
