import{buildEarthElemental}from'./earth.mjs';import * as THREE from 'three';import fs from'node:fs';import sharp from'sharp';
const g=buildEarthElemental(),mix=new THREE.AnimationMixer(g.object),mesh=g.object.getObjectByName('earth_elemental_original_body'),p=mesh.geometry.attributes.position,report={};let maxError=0,sumError2=0,num=0;
for(const clip of g.clips){const a=mix.clipAction(clip);a.setLoop(THREE.LoopOnce,1);a.clampWhenFinished=true;a.play();let min=Infinity,max=-Infinity;
 for(let frame=0;frame<=32;frame++){mix.setTime(clip.duration*frame/32);g.object.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(g.object,true);min=Math.min(min,box.min.y);max=Math.max(max,box.min.y);const mats=mesh.skeleton.bones.map((b,i)=>new THREE.Matrix4().multiplyMatrices(b.matrixWorld,mesh.skeleton.boneInverses[i]));
  for(let i=0;i<p.count;i++){const base=new THREE.Vector3().fromBufferAttribute(p,i).applyMatrix4(mesh.bindMatrix),full=new THREE.Vector3();for(const [bone,w]of mesh._sourceFullWeights[i])full.addScaledVector(base.clone().applyMatrix4(mats[bone]),w);full.applyMatrix4(mesh.bindMatrixInverse).applyMatrix4(mesh.matrixWorld);const actual=mesh.getVertexPosition(i,new THREE.Vector3()).applyMatrix4(mesh.matrixWorld);const err=full.distanceTo(actual);maxError=Math.max(maxError,err);sumError2+=err*err;num++;}
 }if(min<-.002||!Number.isFinite(min))throw new Error(`${clip.name} floor ${min}`);report[clip.name]={minFloor:min,maxFloor:max};a.stop();}
report.weightError={maxMeters:maxError,rmsMeters:Math.sqrt(sumError2/num),samples:num};
mix.clipAction(g.clips[0]).play();mix.setTime(.3);g.object.updateMatrixWorld(true);
const tex=await sharp(g.meta.textureBindings[0].baseColorPath).raw().toBuffer({resolveWithObject:true});
for(const [view,angle]of [['front',0],['side',Math.PI/2]]){const faces=[],points=Array.from({length:p.count},(_,i)=>mesh.getVertexPosition(i,new THREE.Vector3()).applyMatrix4(mesh.matrixWorld).applyAxisAngle(new THREE.Vector3(0,1,0),angle));for(let i=0;i<p.count;i+=3){const vs=points.slice(i,i+3),n=new THREE.Vector3().crossVectors(vs[1].clone().sub(vs[0]),vs[2].clone().sub(vs[0])).normalize();const uv=mesh.geometry.attributes.uv;let u=0,v=0;for(let k=0;k<3;k++){u+=uv.getX(i+k)/3;v+=uv.getY(i+k)/3;}let x=Math.max(0,Math.min(tex.info.width-1,Math.floor(u*tex.info.width))),y=Math.max(0,Math.min(tex.info.height-1,Math.floor(v*tex.info.height)));const off=(y*tex.info.width+x)*tex.info.channels,shade=.55+.6*Math.abs(n.dot(new THREE.Vector3(-.3,.6,.7).normalize())),c=Array.from(tex.data.subarray(off,off+3)).map(x=>Math.min(255,Math.round(x*shade)));faces.push({z:vs.reduce((a,v)=>a+v.z,0),svg:`<polygon points="${vs.map(v=>`${380+v.x*185},${560-v.y*185}`).join(' ')}" fill="rgb(${c})"/>`});}await sharp(Buffer.from(`<svg width="760" height="620" xmlns="http://www.w3.org/2000/svg"><rect width="760" height="620" fill="#bdcbd2"/>${faces.sort((a,b)=>a.z-b.z).map(f=>f.svg).join('')}</svg>`)).png().toFile(`test-results/earth-elemental-source/${view}.png`);}
fs.writeFileSync('test-results/earth-elemental-source/cpu-check.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
