import sharp from 'sharp';import fs from 'node:fs';import path from 'node:path';import * as THREE from 'three';
const source=JSON.parse(fs.readFileSync(new URL('./derived/source.json',import.meta.url),'utf8'));
const root=path.resolve('test-results/richer-creatures-source-cache/earth-elemental/earth elemental 1.1/textures');
const derived=path.resolve('tools/rpg-bestiary/earth-elemental-source/derived');
// FBX UVs use bottom-origin V; glTF decoded texture rows use top-origin. Flip image rows, retaining source UV/tangent orientation.
for(const [original,output]of [['low poly text.png','source-color-gltf.png'],['low poly normal.png','source-normal-gltf.png']])await sharp(path.join(root,original)).flip().png().toFile(path.join(derived,output));
export function buildEarthElemental(id='stone_golem'){
 const object=new THREE.Group();object.name=id;const motion=new THREE.Group();motion.name='earth_source_ground';object.add(motion);
 const jointIds=new Set(source.meshes.flatMap(m=>m.joints));const nodes=source.nodes.map(n=>{const o=jointIds.has(n.id)?new THREE.Bone():new THREE.Group();o.name=`earth_${n.id}_${n.name.replace(/[^a-zA-Z0-9_]/g,'_')}`;o.position.fromArray(n.position);o.quaternion.fromArray(n.quaternion);o.scale.fromArray(n.scale);return o;});
 for(const n of source.nodes){if(n.parent===null)motion.add(nodes[n.id]);else nodes[n.parent].add(nodes[n.id]);}object.updateMatrixWorld(true);
 const material=new THREE.MeshStandardMaterial({name:'earth_elemental_original_rock',color:0xffffff,roughness:.91,metalness:0,side:THREE.DoubleSide});
 for(const m of source.meshes){const geometry=new THREE.BufferGeometry();for(const [key,name,size,C]of [['positions','position',3,Float32Array],['normals','normal',3,Float32Array],['uvs','uv',2,Float32Array],['skinIndices','skinIndex',4,Uint16Array],['skinWeights','skinWeight',4,Float32Array]])geometry.setAttribute(name,new THREE.BufferAttribute(new C(m[key]),size));
  geometry.computeBoundingBox();const skeleton=new THREE.Skeleton(m.joints.map(i=>nodes[i]),m.inverseBindMatrices.map(a=>new THREE.Matrix4().fromArray(a)));const mesh=new THREE.SkinnedMesh(geometry,material);mesh.name='earth_elemental_original_body';mesh.frustumCulled=false;mesh.castShadow=true;mesh.receiveShadow=true;motion.add(mesh);mesh.bind(skeleton,new THREE.Matrix4());mesh._sourceFullWeights=m.fullWeights;
 }
 const mapping={Idle:'idle',Walk:'walking',Run:'walking',Attack:'right punch',Hit:'take hit',HitLeft:'take hit',HitRight:'take hit',Death:'death'};
 const clips=Object.entries(mapping).map(([name,original])=>{const a=source.clips.find(c=>c.name===original),tracks=[],speed=name==='Run'?.7:1;const times=a.times.map(t=>t*speed);for(const t of a.tracks)for(const [property,size,Type]of [['position',3,THREE.VectorKeyframeTrack],['quaternion',4,THREE.QuaternionKeyframeTrack],['scale',3,THREE.VectorKeyframeTrack]]){const values=t[property];if(values.every((v,i)=>Math.abs(v-values[i%size])<1e-8)&&nodes[t.node][property].toArray().every((v,i)=>Math.abs(v-values[i])<1e-8))continue;tracks.push(new Type(`${nodes[t.node].name}.${property}`,times,values));}return new THREE.AnimationClip(name,times.at(-1),tracks);});
 object.animations=clips;object.updateMatrixWorld(true);const mixer=new THREE.AnimationMixer(object);mixer.clipAction(clips[0]).play();mixer.setTime(0);object.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(object,true);const scale=2.55/box.getSize(new THREE.Vector3()).y;object.scale.setScalar(scale);object.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(object,true);object.position.y=-box.min.y;mixer.stopAllAction();object.updateMatrixWorld(true);
 const floorCorrection={};
 for(const clip of clips){const action=mixer.clipAction(clip);action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.play();const sampleSet=new Set([0,clip.duration]);for(let t=0;t<clip.duration;t+=1/60)sampleSet.add(t);for(const track of clip.tracks)for(const t of track.times)sampleSet.add(t);const times=[],values=[];let maximumLift=0;
  for(const time of [...sampleSet].sort((a,b)=>a-b)){mixer.setTime(time);object.updateMatrixWorld(true);const floor=new THREE.Box3().setFromObject(object,true).min.y,lift=Math.max(0,.003-floor);times.push(time);values.push(0,lift/scale,0);maximumLift=Math.max(maximumLift,lift);}action.stop();mixer.uncacheClip(clip);clip.tracks.push(new THREE.VectorKeyframeTrack('earth_source_ground.position',times,values));floorCorrection[clip.name]={samples:times.length,maximumLift};
 }mixer.stopAllAction();object.updateMatrixWorld(true);
 const meta={floorCorrection,family:'golem',height:2.55,source:'Earth Elemental / Golem by piacenti, original first body',license:'CC-BY-3.0',rig:'original-earth-elemental-63-joint',provenance:{url:'https://opengameart.org/content/earth-elemental-golem',author:'piacenti',license:'CC-BY-3.0',attribution:'Earth Elemental / Golem by piacenti, https://opengameart.org/content/earth-elemental-golem, CC BY 3.0. Converted from original FBX; clips sliced by source Unity metadata, normalized to 2.55m, runtime skin weights refit to four with measured error, floor correction, texture rows adapted for glTF. Geometry and native rig retained.',sourceFiles:source.sourceFiles,conversion:'ufbx 0.0.5 isolated Windows Python wheel; FBX6100 ASCII; source UVs/normals and 63 native joints preserved',weightReduction:source.weightReduction},textureBindings:[{materialName:material.name,baseColorPath:path.join(derived,'source-color-gltf.png'),normalPath:path.join(derived,'source-normal-gltf.png'),flipY:false}],clipProvenance:Object.entries(mapping).map(([name,original])=>({name,source:original,...Object.fromEntries(['take','firstFrame','lastFrame','fps'].map(k=>[k,source.clips.find(c=>c.name===original)[k]])),derivation:name==='Run'?'Source walking at 1/0.7 speed; no native run take':name==='HitLeft'||name==='HitRight'?'Alias of native take hit; no native directional hit takes':'Original source take'})),sourceAnimationCount:source.clips.length,attackContact:.45,animationAcceptance:'candidate-needs-browser-review',textureOrientation:'Original FBX UVs preserved; source base-color and normal image rows flipped once for glTF sampling',revision:'earth-elemental-source-1'};
 return {object,clips,meta};
}
