import sharp from 'sharp';import fs from 'node:fs';import path from 'node:path';import * as THREE from 'three';
const source=JSON.parse(fs.readFileSync(new URL('./derived/source.json',import.meta.url),'utf8'));
const root=path.resolve('tools/rpg-bestiary/beetle-golem-source/derived');
const derived=path.resolve('tools/rpg-bestiary/beetle-golem-source/derived');
// Blender UVs use bottom-origin V; glTF decoded texture rows use top-origin. Flip image rows, retaining source UV/tangent orientation.
for(const [original,output]of [['original-map-1.png','source-color-gltf.png'],['original-map-0.png','source-normal-gltf.png']])await sharp(path.join(root,original)).flip().png().toFile(path.join(derived,output));
export function buildBeetleGolem(id='stone_golem'){
 const object=new THREE.Group();object.name=id;const motion=new THREE.Group();motion.name='beetle_source_ground';object.add(motion);
 const jointIds=new Set(source.meshes.flatMap(m=>m.joints));const nodes=source.nodes.map(n=>{const o=jointIds.has(n.id)?new THREE.Bone():new THREE.Group();o.name=`beetle_${n.id}_${n.name.replace(/[^a-zA-Z0-9_]/g,'_')}`;o.position.fromArray(n.position);o.quaternion.fromArray(n.quaternion);o.scale.fromArray(n.scale);return o;});
 for(const n of source.nodes){if(n.parent===null)motion.add(nodes[n.id]);else nodes[n.parent].add(nodes[n.id]);}object.updateMatrixWorld(true);
 const material=new THREE.MeshStandardMaterial({name:'beetle_golem_original_rock',color:0xffffff,roughness:.55,metalness:0,side:THREE.DoubleSide});
 for(const m of source.meshes){const geometry=new THREE.BufferGeometry();for(const [key,name,size,C]of [['positions','position',3,Float32Array],['normals','normal',3,Float32Array],['uvs','uv',2,Float32Array],['skinIndices','skinIndex',4,Uint16Array],['skinWeights','skinWeight',4,Float32Array]])geometry.setAttribute(name,new THREE.BufferAttribute(new C(m[key]),size));
  geometry.computeBoundingBox();const skeleton=new THREE.Skeleton(m.joints.map(i=>nodes[i]),m.inverseBindMatrices.map(a=>new THREE.Matrix4().fromArray(a)));const mesh=new THREE.SkinnedMesh(geometry,material);mesh.name='beetle_golem_original_body';mesh.frustumCulled=false;mesh.castShadow=true;mesh.receiveShadow=true;motion.add(mesh);mesh.bind(skeleton,new THREE.Matrix4());mesh._sourceFullWeights=m.fullWeights;
 }
 const mapping={Idle:'Idle_Normal',Walk:'Walk',Run:'Walk',Attack:'Attack1',Hit:'Hurt1',HitLeft:'Hurt1',HitRight:'Hurt2',Death:'Death'};
 const clips=Object.entries(mapping).map(([name,original])=>{const a=source.clips.find(c=>c.name===original),tracks=[],speed=name==='Run'?.7:1;const times=a.times.map(t=>t*speed);for(const t of a.tracks)for(const [property,size,Type]of [['position',3,THREE.VectorKeyframeTrack],['quaternion',4,THREE.QuaternionKeyframeTrack],['scale',3,THREE.VectorKeyframeTrack]]){const values=t[property];if(values.every((v,i)=>Math.abs(v-values[i%size])<1e-8)&&nodes[t.node][property].toArray().every((v,i)=>Math.abs(v-values[i])<1e-8))continue;tracks.push(new Type(`${nodes[t.node].name}.${property}`,times,values));}return new THREE.AnimationClip(name,times.at(-1),tracks);});
 object.animations=clips;object.updateMatrixWorld(true);const mixer=new THREE.AnimationMixer(object);mixer.clipAction(clips[0]).play();mixer.setTime(0);object.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(object,true);const scale=2.55/box.getSize(new THREE.Vector3()).y;object.scale.setScalar(scale);object.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(object,true);object.position.y=-box.min.y;mixer.stopAllAction();object.updateMatrixWorld(true);
 const floorCorrection={};
 for(const clip of clips){const action=mixer.clipAction(clip);action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.play();const sampleSet=new Set([0,clip.duration]);for(let t=0;t<clip.duration;t+=1/60)sampleSet.add(t);for(const track of clip.tracks)for(const t of track.times)sampleSet.add(t);const times=[],values=[];let maximumLift=0;
  for(const time of [...sampleSet].sort((a,b)=>a-b)){mixer.setTime(time);object.updateMatrixWorld(true);const floor=new THREE.Box3().setFromObject(object,true).min.y,lift=Math.max(0,.003-floor);times.push(time);values.push(0,lift/scale,0);maximumLift=Math.max(maximumLift,lift);}action.stop();mixer.uncacheClip(clip);clip.tracks.push(new THREE.VectorKeyframeTrack('beetle_source_ground.position',times,values));floorCorrection[clip.name]={samples:times.length,maximumLift};
 }mixer.stopAllAction();object.updateMatrixWorld(true);
 const meta={family:'golem',height:2.55,rig:'original-beetle-golem-29-joint',source:'Beetle Golem by killyoverdrive, animated by Dm3d',license:'CC-BY-SA-3.0',floorCorrection,sourceFacts:source.sourceFacts,provenance:{url:'https://opengameart.org/content/beetle-golem-animated',originalUrl:'https://opengameart.org/content/beetle-golem-0',author:'killyoverdrive',animator:'Dm3d',license:'CC-BY-SA-3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',attribution:'Beetle Golem by killyoverdrive, animated by Dm3d. https://opengameart.org/content/beetle-golem-animated. CC BY-SA 3.0. Converted from original Blender file; native rig and texture channels retained, four-influence skinning conversion, 2.55m scale, floor correction and runtime clip aliases. This adapted creature asset is CC BY-SA 3.0.',sourceFiles:source.sourceFiles,modifications:'Blender Z-up to glTF Y-up conversion, original packed color/normal maps with flipped rows for glTF, original animation poses sampled at48Hz with native24fps action timing, normalization and floor correction. No grafts or authored body edits.',weightReduction:source.weightReduction},textureBindings:[{materialName:material.name,baseColorPath:path.join(derived,'source-color-gltf.png'),normalPath:path.join(derived,'source-normal-gltf.png'),flipY:false}],clipProvenance:Object.entries(mapping).map(([name,original])=>({name,source:original,...Object.fromEntries(['firstFrame','lastFrame','fps','sampleFps'].map(k=>[k,source.clips.find(c=>c.name===original)[k]])),derivation:name==='Run'?'Faster source Walk at1/0.7speed; no native Run':name==='Hit'?'Alias of native Hurt1; directional native Hurt1/Hurt2 retained as HitLeft/HitRight':'Native action'})),sourceAnimationCount:source.clips.length,attackContact:.5,animationAcceptance:'candidate-needs-production-browser-review',revision:'beetle-golem-source-1'};
 return {object,clips,meta};
}

