/** Authored attack contact poses from the base motion rebuild and exported creature expansion metadata. */
export const CREATURE_MOTION_TIMING: Record<string, { seconds: number; contactNormalized: number }> = {
  "animal_aurochs": { seconds: 1.8, contactNormalized: 0.575 },
  "animal_bear": { seconds: 2.466667, contactNormalized: 0.15 },
  "animal_boar": { seconds: 0.7, contactNormalized: 0.7 },
  "animal_cattle": { seconds: 1.8, contactNormalized: 0.575 },
  "animal_chicken": { seconds: 0.7, contactNormalized: 0.43 },
  "animal_chicken_speckled": { seconds: 0.7, contactNormalized: 0.43 },
  "animal_coyote": { seconds: 1.4, contactNormalized: 0.525 },
  "animal_crab": { seconds: 0.88, contactNormalized: 0.43 },
  "animal_deer": { seconds: 1.08, contactNormalized: 0.43 },
  "animal_frog": { seconds: 0.68, contactNormalized: 0.43 },
  "animal_frog_green": { seconds: 0.68, contactNormalized: 0.43 },
  "animal_goat": { seconds: 1.466667, contactNormalized: 0.55 },
  "animal_hog": { seconds: 0.86, contactNormalized: 0.43 },
  "animal_ibex": { seconds: 1.533333, contactNormalized: 0.55 },
  "animal_rabbit": { seconds: 0.66, contactNormalized: 0.43 },
  "animal_rabbit_dark": { seconds: 0.66, contactNormalized: 0.43 },
  "animal_rat": { seconds: 0.58, contactNormalized: 0.43 },
  "animal_scorpion": { seconds: 0.8, contactNormalized: 0.45 },
  "animal_viper": { seconds: 1.666667, contactNormalized: 0.525 },
  // Remeasured off the repaired Attack, where the horn actually crosses the target: 0.7 was a
  // third of a second after the strike had already swept past and started back down. Measured
  // offline by `tools/creature-motion/rhino-contact.ts` and confirmed in the production combat
  // lab, where the observed damage lands at normalized 0.392 once the simulation tick quantizes
  // it (test-results/rhino-{air,earth,water}-attack).
  "boss_rhino_air": { seconds: 1.233333, contactNormalized: 0.33229264631653577 },
  "boss_rhino_earth": { seconds: 1.233333, contactNormalized: 0.33229264631653577 },
  "boss_rhino_water": { seconds: 1.233333, contactNormalized: 0.33229264631653577 },
  "creature_redbrush_fox": { seconds: 0.88, contactNormalized: 0.49 },
  "creature_duskoak_lynx": { seconds: 1.02, contactNormalized: 0.43 },
  "creature_rootdelve_badger": { seconds: 1.1, contactNormalized: 0.46 },
  "creature_quillback_porcupine": { seconds: 1.16, contactNormalized: 0.54 },
  "creature_marchwild_horse": { seconds: 1.18, contactNormalized: 0.46 },
  "creature_cairn_bighorn": { seconds: 1.05, contactNormalized: 0.46 },
  "creature_marsh_moose": { seconds: 1.23, contactNormalized: 0.47 },
  "creature_bracken_tapir": { seconds: 0.9, contactNormalized: 0.48 },
  "creature_reedjaw_crocodile": { seconds: 0.833333, contactNormalized: 0.458333 },
  "creature_kiln_salamander": { seconds: 1.08, contactNormalized: 0.43 },
  "creature_slateback_tortoise": { seconds: 1.45, contactNormalized: 0.49 },
  "creature_ashscale_monitor": { seconds: 1.1, contactNormalized: 0.48 },
  "creature_reedbank_goose": { seconds: 1.14, contactNormalized: 0.46 },
  "creature_blackwater_heron": { seconds: 1.05, contactNormalized: 0.455 },
  "creature_scree_bustard": { seconds: 0.8, contactNormalized: 0.455 },
  "creature_marchfield_turkey": { seconds: 0.78, contactNormalized: 0.455 },
  "creature_quarry_snail": { seconds: 1.5, contactNormalized: 0.48 },
  "creature_antler_beetle": { seconds: 1.1, contactNormalized: 0.5 },
  "creature_slag_centipede": { seconds: 0.94, contactNormalized: 0.5 },
  "creature_hollowroot_spider": { seconds: 1.04, contactNormalized: 0.5 },
  "creature_cinder_ravager": { seconds: 2.333333, contactNormalized: 0.235 },
  "creature_basalt_drake": { seconds: 1.6, contactNormalized: 0.65 },
  "creature_gorge_mantis": { seconds: 1, contactNormalized: 0.316667 },
  "creature_quarry_nightmare": { seconds: 1.2, contactNormalized: 0.72 },
};
