/** Display copy only. Authored IDs, asset paths, save keys and table keys stay unchanged. */
export const DISPLAY_NAME_REPLACEMENTS: Readonly<Record<string, string>> = Object.freeze({
  // Materials apply to their ore, bar, tool, weapon, armour and recipe compounds.
  Grithe: "Copper",
  Corven: "Iron",
  Kaldite: "Cobalt",
  Emberite: "Titanium",
  Palewood: "Oak",
  Duskoak: "Maple",
  Cairnpine: "Pine",
  Cinderpine: "Cedar",
  "March Stone": "Limestone",
  Marchstone: "Limestone",
  Kilnstones: "Flux Stones",
  Kilnstone: "Flux Stone",
  "Pale Quartz": "Quartz",
  "Vell Amber": "Amber",
  "Cairn Garnet": "Garnet",
  "Bramble Hides": "Thick Hides",
  "Bramble Hide": "Thick Hide",
  "Cairn Pelts": "Fur Pelts",
  "Cairn Pelt": "Fur Pelt",
  Marchhide: "Hide",
  Bramblehide: "Thick Hide",
  Cairnpelt: "Fur",
  Charhides: "Heavy Hides",
  Charhide: "Heavy Hide",
  "Ember Haunch": "Prime Haunch",
  "Silt Minnows": "Minnows",
  "Silt Minnow": "Minnow",
  "Bramble Trout": "Trout",
  Cragfin: "Perch",
  Ashfin: "Bass",

  // Towns and regions retain separate, stable identities.
  Coldbrace: "Millfield",
  Rootfall: "Oakwood",
  Highcairn: "Hillcrest",
  Emberfast: "Ashford",
  Fallowmarch: "Farmland",
  Vellenwood: "Woodlands",
  Karrowmoor: "Highlands",
  Kilnhalt: "Ashlands",
  "The Gravelmaw": "Stone Cavern",
  Gravelmaw: "Stone Cavern",

  // Specific landmarks precede material/species terms in the phrase matcher.
  "March Road": "Farm Road",
  "March Company": "Trade Company",
  "Bracken Pit": "Copper Pit",
  "Palewood Copse": "Oak Grove",
  "Duskoak Stand": "Maple Grove",
  "Cinderpine Stand": "Cedar Grove",
  "Corven Ford": "River Crossing",
  "Marchfield Farmstead": "Meadow Farm",
  Marchfield: "Farm Fields",
  "The Open March": "Open Meadow",
  "Open March": "Meadow",
  "Brookvault Planks": "Brook Planks",
  "Hollowcut Seam": "Forest Quarry",
  Hollowcut: "Forest Quarry",
  "Mire Skirt": "Marsh Edge",
  "The Thornline": "The Thicket",
  Thornline: "Thicket",
  Marchgate: "Forest Gate",
  Moorgate: "Highland Gate",
  "Cairn Gate": "Mountain Gate",
  "Upper Karrow Seam": "Upper Cobalt Seam",
  "Cairn Tarns": "Mountain Lakes",
  "Cairn Tarn": "Mountain Lake",
  "Far Tarn": "Far Lake",
  "Tarn Track": "Lake Trail",
  "Sunder Ledge": "Broken Ledge",
  "Scree Slide": "Rockslide",
  "Ember Edge": "Ash Border",
  Kilnroad: "Kiln Road",
  "Clinker Quarry": "Volcanic Quarry",
  "Clinker Rows": "Quarry Seams",
  "Ashfin Springs": "Hot Springs",
  "Ashfin Spring": "Hot Spring",
  Redsill: "River",
  Karrow: "Highland",

  // Creature names follow the shipped model anatomy; tier variants remain distinct.
  "Redsill Frog": "Frog",
  "Redsill Frogs": "Frogs",
  "Marchfield Hen": "Hen",
  "Bracken Hen": "Speckled Hen",
  "Open March Billy": "Goat",
  "Marchfield Cow": "Cow",
  "Marchfield Coney": "Rabbit",
  "Palewood Adder": "Viper",
  "March Road Reaver": "Road Bandit",
  "Duskoak Stag": "Stag",
  "Bramble Hog": "Pig",
  "Bramble Hogs": "Pigs",
  "Deepwood Coyote": "Forest Wolf",
  "Blackwater Frog": "Green Frog",
  "Rootfall Coney": "Forest Rabbit",
  "Thornline Adder": "Forest Viper",
  "Gorge Reaver": "Forest Bandit",
  "Highcairn Bear": "Brown Bear",
  "Scree Boar": "Wild Boar",
  "Ridge Ibex": "Ibex",
  "Terrace Aurochs": "Aurochs",
  "Karrow Reaver": "Highland Bandit",
  "Tarn Coyote": "Dire Wolf",
  "Gravelmaw Rat": "Giant Rat",
  "Gravelmaw Rats": "Giant Rats",
  "Quarry Scorpion": "Giant Scorpion",
  "Sump Crab": "Giant Crab",
  "Gravelmaw Cave Bear": "Cave Bear",
  "Ashback Bear": "Dire Bear",
  "Cinder Boar": "Dire Boar",
  "Emberhorn Ibex": "Large Ibex",
  "Cinder Adder": "Giant Viper",
  "Kilnroad Reaver": "Quarry Bandit",
  "Redbrush Fox": "Red Fox",
  "Duskoak Lynx": "Lynx",
  "Rootdelve Badger": "Badger",
  "Quillback Porcupine": "Porcupine",
  "Marchwild Horse": "Wild Horse",
  "Cairn Bighorn Sheep": "Bighorn Sheep",
  "Marsh Moose": "Moose",
  "Bracken Tapir": "Tapir",
  "Reedjaw Crocodile": "Crocodile",
  "Kiln Salamander": "Salamander",
  "Slateback Tortoise": "Tortoise",
  "Ashscale Monitor": "Monitor Lizard",
  "Reedbank Goose": "Goose",
  "Blackwater Heron": "Heron",
  "Scree Bustard": "Bustard",
  "Marchfield Turkey": "Turkey",
  "Quarry Snail": "Snail",
  "Antler Stag Beetle": "Stag Beetle",
  "Slag Centipede": "Giant Centipede",
  "Hollowroot Spider": "Giant Spider",
  "Cinder Ravager": "Armored Demon",
  "Basalt Drake": "Armored Dragon",
  "Gorge Mantis": "Giant Mantis",
  "Quarry Nightmare": "Pale Dragon",
  "Tempest Roc": "Storm Rhino",
  Roc: "Storm Rhino",
  "The Rootheart": "Stone Rhino",
  Rootheart: "Stone Rhino",
  "Ordrun the Quarrykeeper": "Armored Rhino",
  Ordrun: "Armored Rhino",
  Quarrykeeper: "Armored Rhino",
  Galeskin: "Plains Ogre",
  Mossbound: "Forest Ogre",
  Tideworn: "Cave Ogre",
  Cinderwake: "Fire Ogre",

  // Loot and crafting copy must agree with its source creature.
  "Coney Foot": "Rabbit Foot",
  "Coyote Fang": "Wolf Fang",
  "Ashback Claw": "Dire Bear Claw",
  "Cinder Tusk": "Dire Boar Tusk",
  Emberhorn: "Large Ibex Horn",
  "Kiln Fang": "Giant Viper Fang",
  "Fox Guardhair": "Fox Fur",
  "Foxhair Ring": "Fox Fur Ring",
  "Horse Tailhair": "Horsehair",
  "Bighorn Fleece": "Bighorn Wool",
  "Moose Antler Palm": "Moose Antler",
  "Crocodile Scute": "Crocodile Armor Plate",
  "Monitor Sinew": "Monitor Lizard Sinew",
  "Turkey Tailfeather": "Turkey Tail Feather",
  "Beetle Mandible": "Beetle Jaw",
  "Spider Thread": "Spider Silk",
  "Ravager Talon": "Demon Claw",
  "Drake Scale": "Armored Dragon Scale",
  "Drake Hide": "Armored Dragon Hide",
  "Mantis Scythe": "Mantis Claw",
  "Nightmare Plate": "Pale Dragon Plate",
  "Nightmare-plated": "Pale Dragon Plated",
  "Talon-gripped": "Demon Claw Grip",
  "Quillguard Ring": "Porcupine Quill Ring",
  "Antler Palm Charm": "Antler Charm",

  // Prose uses these ordinary singular/plural forms outside full species names.
  Coneys: "Rabbits",
  Coney: "Rabbit",
  Coyotes: "Wolves",
  Coyote: "Wolf",
  Reavers: "Bandits",
  Reaver: "Bandit",
  Adders: "Vipers",
  Adder: "Viper",
  Harts: "Stags",
  Hart: "Stag",
});

const replacementByLowercase = new Map(
  Object.entries(DISPLAY_NAME_REPLACEMENTS).map(([from, to]) => [from.toLowerCase(), to]),
);
const phrases = [...replacementByLowercase.keys()]
  .sort((a, b) => b.length - a.length || (a < b ? -1 : a > b ? 1 : 0))
  .map((phrase) => phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
// Backtick spans can contain authoritative IDs, including bare names such as `ordrun`.
const displayPhrase = new RegExp("(`+)[\\s\\S]*?\\1|(?<![\\p{L}\\p{N}_])(?:" + phrases.join("|") + ")(?![\\p{L}\\p{N}_])", "giu");

/** Format a display leaf once; never pass IDs/keys or traverse an entire content object. */
export function plainDisplayText(text: string): string {
  return text.replace(displayPhrase, (match: string) => {
    if (match.startsWith("`")) return match;
    const replacement = replacementByLowercase.get(match.toLowerCase())!;
    if (match === match.toLowerCase()) return replacement.toLowerCase();
    if (match === match.toUpperCase()) return replacement.toUpperCase();
    return replacement;
  });
}
