import type { RegionId, SolidVolume, Vec3 } from "../contracts.js";
import { GAME_BOOT_PROFILE } from "../app/bootProfile.js";
import { buildDungeonSpec } from "../app/dungeonSpec.js";
import { fishingSiteAnchors } from "../app/fishingAccess.js";
import { registerHabitatClearances } from "../app/habitatClearances.js";
import { miningAccessPositions } from "../app/miningAccess.js";
import { mobSpawnPlacementPorts, prepareMobSpawns } from "../app/mobSpawns.js";
import { REGIONS } from "../content/regions.js";
import { WORLD_HABITATS, type HabitatDef } from "../content/worldHabitats.js";
import { WORLD_SITES } from "../content/worldSites.js";
import type { WaterBodySnapshot } from "../render/scene.js";
import type { Navigation } from "../systems/navigation.js";
import { Solids } from "../systems/solids.js";
import { authoredThresholds, DungeonDoors } from "../world/dungeonDoors.js";
import { chamberFloorAt, dungeonFloorHeight } from "../world/dungeonLayout.js";
import { ForestObstacles } from "../world/forestObstacles.js";
import { ForestResources, type ForestTreeDescriptor } from "../world/forestResources.js";
import { lavaObstacles } from "../world/lavaObstacles.js";
import type { BuiltWorld } from "../world/regionBuilder.js";
import type { GroundSample, PlacementTerrain } from "../world/terrainSampler.js";
import { TreeClearances } from "../world/treeClearance.js";
import type { HeadlessWorldPorts } from "./headlessWorld.js";
import { planSpawns, type SpawnContext } from "./spawnPlan.js";

/**
 * The authored world, assembled from ground queries and prepared geometry.
 *
 * Two callers feed it. The bake builds the terrain and the GLB geometry with the renderer's code and
 * writes what it produced into the server world pack. The server reads the pack. Both then run the
 * steps in this file, so the live catalog and the world seed decide the entities, the spawn plan and
 * the tree clearances at every boot, and nothing here loads a renderer.
 */

/** Ground queries of one terrain map. `WorldScene` and `TerrainSampler` both answer them. */
export interface AssemblyTerrain extends PlacementTerrain {
  heightAt(regionId: RegionId, x: number, z: number): number;
  normalAt(x: number, z: number): Vec3;
  regionAt(x: number, z: number): RegionId;
  sampleWorld(x: number, z: number): GroundSample;
  getWaterBodies(): WaterBodySnapshot[];
  getRoadPolylines(): Vec3[][];
}

export interface AssemblyTerrains {
  main: AssemblyTerrain;
  fairy: AssemblyTerrain;
  /** The fairy map's whole extent, coast collar included. A point inside it belongs to the fairy map. */
  fairyExtent: { minX: number; maxX: number; minZ: number; maxZ: number };
}

export interface AssetMeasurements {
  baseY(assetId: string): number;
  assetSize(assetId: string): { x: number; y: number; z: number } | null;
  assetCenterXZ(assetId: string): { x: number; z: number } | null;
}

/** The manifest fields the measurements come from. The world pack stores exactly these for every asset. */
export interface AssetMeasure {
  size: { x: number; y: number; z: number };
  base?: { x: number; y: number; z: number };
  groundY?: number;
}

export function assetMeasurements(entry: (assetId: string) => AssetMeasure | undefined): AssetMeasurements {
  return {
    baseY: id => { const found = entry(id); return found?.groundY ?? found?.base?.y ?? 0; },
    assetSize: id => entry(id)?.size ?? null,
    assetCenterXZ: id => { const found = entry(id); return found ? { x: (found.base?.x ?? -found.size.x / 2) + found.size.x / 2, z: (found.base?.z ?? -found.size.z / 2) + found.size.z / 2 } : null; },
  };
}


export interface Bounds3 { min: Vec3; max: Vec3 }

/** What only the bake can produce, because it needs model triangles or the scatter. */
export interface AuthoredGeometry {
  /** Generated by the bake or imported from the pack. The assembly adds the route graph and the door constraint. */
  nav: Navigation;
  /** Site dressing, mine cut faces and fairy dressing, in build order. They follow the semantic and lava solids. */
  solids: readonly SolidVolume[];
  /** Boxes around walkable structures, already padded, where a mover keeps the navmesh height. */
  structureBounds: readonly Bounds3[];
  /** Trees scattered around the static exclusions only. The assembly removes the ones in a creature's way. */
  trees: readonly ForestTreeDescriptor[];
}

export interface AuthoredSemantic {
  built: BuiltWorld;
  /** The catalog's authored habitats. */
  habitats: HabitatDef[];
}

export function terrainAtOf(terrains: AssemblyTerrains): (x: number, z: number) => AssemblyTerrain {
  const extent = terrains.fairyExtent;
  return (x, z) => x >= extent.minX && x <= extent.maxX && z >= extent.minZ && z <= extent.maxZ ? terrains.fairy : terrains.main;
}

/** Entities, their solids, the route graph and the authored habitats, from the installed catalog and the seed. */
export function buildAuthoredSemantic(seed: number, terrains: AssemblyTerrains, measurements: AssetMeasurements): AuthoredSemantic {
  const terrainAt = terrainAtOf(terrains);
  const heightAt = (region: RegionId, x: number, z: number) => terrainAt(x, z).heightAt(region, x, z);
  const meshHeightAt = (x: number, z: number) => terrainAt(x, z).meshHeightAt(x, z);
  const roadPolylines = [...terrains.main.getRoadPolylines(), ...terrains.fairy.getRoadPolylines()];
  const roadDistance = (x: number, z: number) => {
    let best = Infinity;
    for (const line of roadPolylines) for (let i = 0; i < line.length - 1; i++) {
      const a = line[i]!, b = line[i + 1]!; const dx = b[0] - a[0], dz = b[2] - a[2];
      const t = Math.max(0, Math.min(1, ((x - a[0]) * dx + (z - a[2]) * dz) / (dx * dx + dz * dz || 1)));
      best = Math.min(best, Math.hypot(x - a[0] - t * dx, z - a[2] - t * dz));
    }
    return best;
  };
  const fishing = fishingSiteAnchors(WORLD_SITES, terrains.main.getWaterBodies(), meshHeightAt);
  const built = GAME_BOOT_PROFILE.buildSemanticWorld(seed, heightAt, { ...measurements, heightAt, roadDistance, dungeonGates: true,
    accessPositions: new Map([...fishing.banks, ...miningAccessPositions(WORLD_SITES, meshHeightAt, measurements)]),
    fishingSchools: fishing.schools,
    minibossCanStand: (region, x, z) => { const sample = terrainAt(x, z).sampleWorld(x, z); return sample.playable && sample.semanticRegion === region && sample.waterBodyId === null && sample.slope !== null && sample.slope <= .5; } });
  const lava = GAME_BOOT_PROFILE.terrain().lavaChannels;
  if (lava?.length) built.solids.push(...lavaObstacles(lava, meshHeightAt));
  return { built, habitats: [...WORLD_HABITATS] };
}

/** Adds the prepared geometry to the semantic world, places the creatures, and returns what a `HeadlessWorld` runs on. */
export function assembleAuthoredWorld(seed: number, terrains: AssemblyTerrains, measurements: AssetMeasurements,
  semantic: AuthoredSemantic, geometry: AuthoredGeometry): HeadlessWorldPorts {
  const { built } = semantic, { nav } = geometry;
  const terrainAt = terrainAtOf(terrains);
  const heightAt = (region: RegionId, x: number, z: number) => terrainAt(x, z).heightAt(region, x, z);
  built.solids.push(...geometry.solids);
  const spec = buildDungeonSpec(terrains.main);
  const dungeonRegion = REGIONS.find(region => region.dungeon);
  const thresholds = dungeonRegion?.dungeon ? authoredThresholds(dungeonRegion.dungeon, heightAt(dungeonRegion.id, ...dungeonRegion.dungeon.entrance)) : [];
  const doorBarriers = thresholds.map(threshold => threshold.barrier);
  nav.setRouteGraph(built.routeNodes, built.routeEdges);
  const doors = new DungeonDoors(doorBarriers, id => built.entities.find(entity => entity.id === id));
  nav.setPathConstraint(path => doors.clipPath(path));
  const placement = { solids: built.solids, scene: terrains.main, nav, dungeonSpec: spec, doorThresholds: thresholds, profile: GAME_BOOT_PROFILE, assetSize: measurements.assetSize, terrainAt };
  const habitats = prepareMobSpawns(built.entities, semantic.habitats, placement);
  // A tree must not stand on a creature's spawn or idle route. The creatures follow the live catalog, so this runs at every boot.
  const clearances = new TreeClearances();
  registerHabitatClearances(nav, built.entities, habitats.filter(h => h.regionId !== spec?.regionId), clearances);
  const trees = geometry.trees.filter(tree => !clearances.blocksTreeClearance(tree.position[0], tree.position[2], tree.trunkRadius));
  // Kept for the life of the world so a content publish can place a few spawn groups again. Trees were cleared
  // around the habitats of the boot catalog and stay where they are, so a new spawn must not land in a trunk.
  let treeCells: Map<string, ForestTreeDescriptor[]> | null = null;
  const treeAt = (x: number, z: number, radius: number): boolean => {
    if (!treeCells) { treeCells = new Map(); for (const tree of trees) { const key = `${Math.floor(tree.position[0] / 8)}:${Math.floor(tree.position[2] / 8)}`; treeCells.set(key, [...treeCells.get(key) ?? [], tree]); } }
    for (let gx = Math.floor((x - radius - 2) / 8); gx <= Math.floor((x + radius + 2) / 8); gx++) for (let gz = Math.floor((z - radius - 2) / 8); gz <= Math.floor((z + radius + 2) / 8); gz++)
      if (treeCells.get(`${gx}:${gz}`)?.some(tree => Math.hypot(tree.position[0] - x, tree.position[2] - z) < radius + tree.trunkRadius)) return true;
    return false;
  };
  const spawnContext: SpawnContext = { seed, baseY: measurements.baseY, assetSize: measurements.assetSize, refinePopulation: true,
    floorAt: (region, x, z) => spec && region === spec.regionId ? dungeonFloorHeight(spec, x, z) : heightAt(region, x, z),
    spacing: () => { const ports = mobSpawnPlacementPorts(placement); return { ...ports, place: (entity, x, z, radius) => treeAt(x, z, radius) ? null : ports.place(entity, x, z, radius) }; } };
  const forestObstacles = new ForestObstacles(); let forest: ForestResources;
  const solids = new Solids(built.solids);
  const structureBounds = geometry.structureBounds;
  const spawn = GAME_BOOT_PROFILE.spawn; const point: Vec3 = [spawn.x, heightAt(spawn.regionId, spawn.x, spawn.z), spawn.z];
  const playable = (region: RegionId, position: Vec3) => spec && region === spec.regionId ? chamberFloorAt(spec, position) !== null :
    terrainAt(position[0], position[2]).sampleWorld(position[0], position[2]).playable && terrainAt(position[0], position[2]).regionAt(position[0], position[2]) === region;
  return { nav, habitats, entities: built.entities, knownLocations: built.knownLocations, doorBarriers, spawn: nav.closestPoint(point) ?? point,
    planSpawns: (world, groupIds, residents) => planSpawns(spawnContext, world, groupIds, residents),
    initialize(world) {
      forest = new ForestResources({ entities: world.entities, getNodeState: id => world.shared.nodes[id], onActivate: tree => { if (world.shared.nodes[tree.id]?.state !== "depleted") forestObstacles.upsert(tree); }, onDeactivate: tree => { forestObstacles.remove(tree.id); } });
      for (const tree of trees) { world.entities.remove(tree.id); forest.register(tree); }
    },
    beforeTick(world) {
      const players = [...world.active].map(id => world.players.get(id)!.store.get()); const pins = new Set<string>();
      for (const player of players) { if (player.player.movement.destinationEntityId) pins.add(player.player.movement.destinationEntityId); if (player.activity?.kind === "gathering") pins.add(player.activity.entityId); }
      forest.updatePlayers(players.map(player => player.player.position), pins);
      forest.forEachResident((entity, tree) => { if (entity.state === "depleted") forestObstacles.remove(tree.id); else forestObstacles.upsert(tree); });
    },
    movement: { solids, authoritativeGround: true, heightAt: (region, x, z) => spec && region === spec.regionId ? dungeonFloorHeight(spec, x, z) : heightAt(region, x, z), dynamicObstacles: forestObstacles,
      preserveNavigationHeight: point => structureBounds.some(box => point[0] >= box.min[0] && point[0] <= box.max[0] && point[1] >= box.min[1] && point[1] <= box.max[1] && point[2] >= box.min[2] && point[2] <= box.max[2]),
      regionAt: (point, current) => current === spec?.regionId ? current : terrainAt(point[0], point[2]).regionAt(point[0], point[2]) },
    campfirePlacement: { withinPlayableBounds: playable,
      groundAt: (region, x, z) => {
        if (spec && region === spec.regionId) { const y = dungeonFloorHeight(spec, x, z); return chamberFloorAt(spec, [x, y, z]) !== null ? { y, normal: [0, 1, 0] } : null; }
        const sample = terrainAt(x, z).sampleWorld(x, z); return sample.playable && sample.semanticRegion === region && !sample.waterBodyId ? { y: terrainAt(x, z).meshHeightAt(x, z), normal: terrainAt(x, z).normalAt(x, z) } : null;
      },
      distanceToWater: (region, point) => {
        if (region === spec?.regionId) return Infinity;
        for (const radius of [0, .2, .4, .6, .8, 1]) for (let i = 0; i < (radius === 0 ? 1 : 32); i++) {
          const sample = terrainAt(point[0], point[2]).sampleWorld(point[0] + Math.sin(i * Math.PI / 16) * radius, point[2] + Math.cos(i * Math.PI / 16) * radius);
          if (!sample.playable || sample.waterBodyId) return radius;
        } return 1.001;
      }, clearAt: (_region, point, radius) => { const resolved = solids.resolve(point, point, radius); return Math.hypot(point[0] - resolved[0], point[2] - resolved[2]) < .001; },
    } };
}
