import assert from 'node:assert/strict';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { startAssetReview } from './server.js';
import { installTestDeadline } from '../lib/deadline.js';

const deadline = installTestDeadline('Temporary asset review', 60000);
const originalManifest = await readFile('game/public/assets/manifest.json');
const server = await startAssetReview(0);
const browser = await chromium.launch({ headless: true, args: ['--enable-gpu', '--ignore-gpu-blocklist', '--use-angle=d3d11', '--mute-audio'] });
const page = await browser.newPage({ viewport: { width: 1680, height: 1050 } });
const errors: string[] = [];
page.on('pageerror', error => errors.push(String(error)));
const out = path.resolve('test-results/asset-review');
await mkdir(out, { recursive: true });
const ready = async () => {
  await page.waitForFunction(() => (window as any).__assetReview?.getState().ready || (window as any).__assetReview?.getState().error, undefined, { timeout: 22000 });
  const state = await page.evaluate(() => (window as any).__assetReview.getState());
  assert.equal(state.error, null); assert(state.ready);
  return state;
};
const frame = () => page.frames().find(frame => frame.url().includes('/index.html?'))!;
const motion = () => frame().evaluate(() => (window as any).__gameDebug.getPlayerMotion());
try {
  await page.goto(server.url);
  const current = await ready();
  assert.equal(current.applied.source, 'current');
  assert.equal(current.applied.mode, 'set');
  const currentMotion = await motion();
  assert(currentMotion.layerAssets.includes('outfit_male_knight_chest'));
  const bounds = await page.locator('#game-frame').boundingBox();
  assert(bounds);
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  for (let i = 0; i < 25; i++) await page.mouse.wheel(0, -100);
  await page.screenshot({ path: path.join(out, 'current.png') });
  await page.locator('#asset-search').fill('grithe_sword');
  await page.locator('#asset-list').selectOption('current:grithe_sword');
  await ready();
  assert(JSON.stringify((await motion()).attachments).includes('corealm_item_grithe_sword'));
  await page.screenshot({ path: path.join(out, 'current-held.png') });
  await page.locator('#asset-counterpart').click();
  const staged = await ready();
  assert.equal(staged.applied.source, 'staged');
  const stagedMotion = await motion();
  assert(JSON.stringify(stagedMotion.attachments).includes('corealm_item_grithe_sword'));
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  for (let i = 0; i < 25; i++) await page.mouse.wheel(0, -100);
  await page.screenshot({ path: path.join(out, 'staged-worn.png') });
  await page.locator('#preview-mode').selectOption('model');
  const model = await ready();
  const gallery = await frame().evaluate(() => (window as any).__environmentLab.getState());
  assert(gallery.assets.includes('corealm_item_grithe_sword'));
  await page.screenshot({ path: path.join(out, 'staged-model.png') });
  await page.locator('#asset-counterpart').click();
  await ready();
  await page.locator('#asset-search').fill('grithe_cuirass');
  await page.locator('#asset-list').selectOption('current:grithe_cuirass');
  await page.locator('#preview-mode').selectOption('set');
  await ready();
  assert((await motion()).layerAssets.includes('outfit_male_knight_chest'));
  const camera = await frame().evaluate(() => {
    const debug = (window as any).__gameDebug;
    return { camera: debug.getCamera(), player: debug.getPlayerPosition() };
  });
  assert(!camera.camera.freeMove);
  assert(camera.camera.requestedDistance >= 6);
  assert(Math.abs(camera.camera.target.y - camera.player.y - 1.1) < .5);
  await page.locator('#asset-search').fill('grithe_ring');
  assert((await page.locator('#asset-list option').count()) >= 2);
  await page.locator('#asset-list').selectOption('current:grithe_ring');
  assert.equal((await ready()).applied.mode, 'model');
  assert.equal(await page.locator('#preview-mode option[value="wear"]').isDisabled(), true);
  assert.deepEqual(await readFile('game/public/assets/manifest.json'), originalManifest);
  assert.deepEqual(errors, []);
  await writeFile(path.join(out, 'report.json'), JSON.stringify({ passed: true, current, staged, model, currentMotion, stagedMotion, gallery, camera, errors, catalogue: { current: server.rows.filter(r => r.source === 'current').length, staged: server.rows.filter(r => r.source === 'staged').length, skipped: server.skipped } }, null, 2));
  console.log(JSON.stringify({ passed: true, rows: server.rows.length, out }));
} finally { await browser.close(); await server.close(); deadline(); }
