import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import * as T from 'three';
import {loadLavaSource} from './source-glb.mjs';
const dir=path.resolve('tools/rpg-bestiary/lava-golem-source/derived'),sha=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
export const lavaGolemProvenance={author:'gavlig',license:'CC0-1.0 model, rig, native animations and supplied glow map; original project procedural replacement rock maps',source:'https://opengameart.org/content/lava-golem',sourceAssets:['golem_clean.blend','golem_emit.png'],sourcePacks:[{id:'gavlig-lava-golem-clean',author:'gavlig',license:'CC0-1.0',source:'https://opengameart.org/content/lava-golem',download:'https://opengameart.org/sites/default/files/golem_clean.blend.zip',sha256:'602e37e8baccc55b6d9778ee2844b27278f8818ddab2fbbaa0b14b0c43a17c81'}],sourceRecords:[{archive:'golem_clean.blend.zip',sha256:'602e37e8baccc55b6d9778ee2844b27278f8818ddab2fbbaa0b14b0c43a17c81',excluded:'Author removed cgtextures-derived diffuse/normal/specular images from official clean archive. Restricted Dropbox full-texture bundle not used.',conceptCredit:'Source page credits Boris concept artwork; model authored by gavlig and official clean asset labeled CC0.'}],modifications:'Complete authored body and 71-bone rig, no anatomy edits or grafts. Source constraints baked by Blender4.5.11. Own deterministic object-space basalt colour/micro-normal maps replace omitted textures. Original glow atlas remains emissive at original slot factor0.9434782266616821. Native idle/walk/smash retained. Running, reactions and death require the studio motion repair profile before promotion. Uniform1.5 source scale and whole-mesh ground alignment.'};
export function buildLavaGolem(id='kiln_marrow'){
  if(id==='lava_golem')throw new Error('The lava_golem selector is retired; use kiln_marrow for the gavlig studio source.');
  const base=loadLavaSource(path.join(dir,'idle.glb')),native={Idle:base.clips[0]};for(const [target,name]of [['Walk','walk'],['Attack','smash']]){const other=loadLavaSource(path.join(dir,`${name}.glb`));if(JSON.stringify(other.nodes.map(n=>n.name))!==JSON.stringify(base.nodes.map(n=>n.name)))throw new Error('Source take node mismatch');native[target]=other.clips[0];}
  const object=new T.Group();object.name=id;const motion=new T.Group();motion.name='lava_ground_motion';object.add(motion);motion.add(base.object);base.object.name='lava_authored_model';base.object.scale.setScalar(1.5);
  for(const mat of base.materials){mat.color.set(0xffffff);mat.roughness=.90;mat.emissive.set(0xffffff);mat.emissiveIntensity=.9434782266616821;}
  const textureBindings=base.materials.map(mat=>({materialName:mat.name,baseColorPath:path.join(dir,'original-basalt-color.png'),normalPath:path.join(dir,'original-basalt-normal.png'),emissivePath:path.join(dir,'golem_emit.png'),emissiveTexCoord:0,emissiveStrength:.9434782266616821,flipY:false}));
  const clone=(src,name,speed=1)=>{const c=native[src].clone();c.name=name;if(speed!==1){for(const t of c.tracks)for(let i=0;i<t.times.length;i++)t.times[i]/=speed;c.duration/=speed;}return c;};
  // This source contains only three genuine takes. The former fast-idle hit and rigid
  // wrapper death were rejected. Export the native source, then complete its motion with
  // tools/tripo-creatures/profiles/studio-animals.ts before devdocs review and promotion.
  const clips=[clone('Idle','Idle'),clone('Walk','Walk'),clone('Attack','Attack')];
  const bounds=()=>{object.updateMatrixWorld(true);const box=new T.Box3();object.traverse(n=>{if(!n.isMesh)return;if(n.isSkinnedMesh)n.skeleton.update();for(let i=0;i<n.geometry.attributes.position.count;i++){const v=new T.Vector3().fromBufferAttribute(n.geometry.attributes.position,i);if(n.isSkinnedMesh)n.applyBoneTransform(i,v);v.applyMatrix4(n.matrixWorld);if(!Number.isFinite(v.x+v.y+v.z))throw new Error('Nonfinite source skinning');box.expandByPoint(v);}});return box;};
  motion.position.y=-bounds().min.y;const checks=[];
  for(const c of clips){const mixer=new T.AnimationMixer(object),a=mixer.clipAction(c);a.setLoop(T.LoopOnce,1);a.clampWhenFinished=true;a.play();const times=[],pos=[],samples=Math.ceil(c.duration*90);let min=Infinity,max=0;for(let i=0;i<=samples;i++){const t=c.duration*i/samples;mixer.setTime(t);const y=bounds().min.y,dy=.003-y;times.push(t);pos.push(0,motion.position.y+dy,0);min=Math.min(min,y);max=Math.max(max,Math.abs(dy));}a.stop();mixer.uncacheRoot(object);c.tracks.push(new T.VectorKeyframeTrack(`${motion.name}.position`,times,pos));checks.push({clip:c.name,rawMinFloor:min,maxAlignment:max});}
  for(const c of clips){const mixer=new T.AnimationMixer(object),a=mixer.clipAction(c);a.setLoop(T.LoopOnce,1);a.clampWhenFinished=true;a.play();let min=Infinity,first,last;for(let i=0;i<=48;i++){mixer.setTime(c.duration*i/48);const b=bounds();min=Math.min(min,b.min.y);if(i===0)first=b.getSize(new T.Vector3()).toArray();if(i===48)last=b.getSize(new T.Vector3()).toArray();}a.stop();mixer.uncacheRoot(object);Object.assign(checks.find(x=>x.clip===c.name),{minFloor:min,firstSize:first,lastSize:last});}
  const size=bounds().getSize(new T.Vector3());let vertices=0,triangles=0;object.traverse(n=>{if(n.isMesh){vertices+=n.geometry.attributes.position.count;triangles+=(n.geometry.index?.count||n.geometry.attributes.position.count)/3;}});
  return {object,clips,meta:{id,family:'lava_golem',revision:'lava-golem-source-review-1',height:size.y,dimensions:size.toArray(),rig:'authored-71-bone-lava-golem',vertices,triangles,source:lavaGolemProvenance.source,license:lavaGolemProvenance.license,provenance:lavaGolemProvenance,textureBindings,sourceMaterial:{originalEmitSlot:{index:3,mapto:65,uv:'active UV layer',texCoord:0,emitfac:.9434782266616821,colfac:1,offset:[0,0,0],scale:[1,1,1],evidence:'test-results/lava-golem-source/legacy-material-slots.json'},replacementRock:{author:'Corealm project original procedural implementation',script:'tools/rpg-bestiary/lava-golem-source/bake-rock.mjs',inputs:'geometry positions/UVs and deterministic 3D noise only; no third-party texture images'},specular:'Removed source photography not used or reinterpreted as roughness',textures:textureBindings.map(b=>Object.fromEntries(Object.entries(b).map(([k,v])=>[k,k.endsWith('Path')?{path:v,sha256:sha(v)}:v])))},clipSources:{Idle:'native idle take at60fps',Walk:'native walk take at60fps',Attack:'native smash take at60fps'},requiredMotionRepair:{profile:'studio',implementation:'tools/tripo-creatures/profiles/studio-animals.ts',missingStates:['Run','Hit','Death']},attackContact:.52,attackContactSource:'Provisional native smash phase0.52; requires production contact review',animationFloorChecks:checks,approval:'native-source-only-needs-studio-motion-repair-and-devdocs-review'}};
}
