/** Focused offline integrity check. Production lab acceptance remains a separate root gate. */
import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { prune } from '@gltf-transform/functions';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import * as T from 'three';
import { readFile,writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
const out='test-results/wilderness-creatures/keepers',catalog=JSON.parse(await readFile(`${out}/catalog.json`,'utf8')),io=new NodeIO().registerExtensions(ALL_EXTENSIONS),expected=['Idle','Walk','Run','Attack','Hit','HitLeft','HitRight','Death'],rows=[];
for(const a of catalog.assets){const bytes=await readFile(`${out}/${catalog.files[a.id]}`);assert.equal(createHash('sha256').update(bytes).digest('hex'),a.sha256);const doc=await io.readBinary(bytes);assert.deepEqual(doc.getRoot().listAnimations().map(a=>a.getName()).sort(),expected.slice().sort());let vertices=0;
 for(const m of doc.getRoot().listMaterials()){assert.equal(m.getMetallicFactor(),0);if(m.getEmissiveFactor().some(v=>v>0)){assert.ok(m.getBaseColorTexture());assert.ok(m.getEmissiveTexture());assert.equal(m.getBaseColorTexture(),m.getEmissiveTexture());assert.ok(m.getExtras().heatAtlas);}else assert.equal(m.getEmissiveTexture(),null);}
 for(const mesh of doc.getRoot().listMeshes())for(const p of mesh.listPrimitives()){const pos=p.getAttribute('POSITION'),weights=p.getAttribute('WEIGHTS_0'),uv=p.getAttribute('TEXCOORD_0'),normal=p.getAttribute('NORMAL');assert.ok(pos&&weights&&normal);if(p.getMaterial().getBaseColorTexture())assert.ok(uv);vertices+=pos.getCount();for(let i=0;i<pos.getCount();i++){const xyz=pos.getElement(i,[]),w=weights.getElement(i,[]),n=normal.getElement(i,[]);assert.ok(xyz.every(Number.isFinite));assert.ok(Math.abs(w.reduce((a,b)=>a+b,0)-1)<1e-5);assert.ok(Math.abs(Math.hypot(...n)-1)<.01);}const tile=p.getMaterial().getExtras().atlasTile??0,col=tile%2,row=Math.floor(tile/2);for(let i=0;i<(uv?.getCount()??0);i++){const [u,v]=uv.getElement(i,[]);assert.ok(u>col*.5+.009&&u<(col+1)*.5-.009);assert.ok(v>row*.5+.009&&v<(row+1)*.5-.009);}}
 for(const m of doc.getRoot().listMaterials())m.setBaseColorTexture(null).setNormalTexture(null).setMetallicRoughnessTexture(null).setEmissiveTexture(null).setOcclusionTexture(null);await doc.transform(prune());const bare=await io.writeBinary(doc),gltf=await new GLTFLoader().parseAsync(bare.buffer.slice(bare.byteOffset,bare.byteOffset+bare.byteLength),''),scene=gltf.scene,mixer=new T.AnimationMixer(scene),clips={};let maximumRadius=0;
 for(const clip of gltf.animations){mixer.stopAllAction();const action=mixer.clipAction(clip).setLoop(T.LoopOnce,1);action.clampWhenFinished=true;action.play();const initial=[];let maxVertexTravel=0,minFloor=Infinity,maxFloor=-Infinity,radius=0;for(let i=0;i<=12;i++){mixer.setTime(clip.duration*i/12);scene.updateMatrixWorld(true);let j=0;scene.traverse(n=>{if(!n.isSkinnedMesh)return;const count=n.geometry.attributes.position.count;for(let k=0;k<count;k+=Math.max(1,Math.floor(count/30))){const v=n.getVertexPosition(k,new T.Vector3()).applyMatrix4(n.matrixWorld);if(i===0)initial.push(v.clone());else maxVertexTravel=Math.max(maxVertexTravel,v.distanceTo(initial[j]));j++;}n.computeBoundingBox();});const b=new T.Box3().setFromObject(scene,true);minFloor=Math.min(minFloor,b.min.y);maxFloor=Math.max(maxFloor,b.min.y);radius=Math.max(radius,Math.hypot(Math.max(Math.abs(b.min.x),Math.abs(b.max.x)),Math.max(Math.abs(b.min.z),Math.abs(b.max.z))));}assert.ok(maxVertexTravel>.008,`${a.id} ${clip.name} has static visible geometry`);assert.ok(minFloor>-.015,`${a.id} ${clip.name} floor penetration${minFloor}`);maximumRadius=Math.max(maximumRadius,radius);clips[clip.name]={seconds:clip.duration,maxVertexTravel,minFloor,maxFloor,radius};}
 rows.push({id:a.id,vertices,triangles:a.triangles,maximumRadius,clips});console.log(`${a.id}: all eight clips visibly deform, ${a.triangles} triangles, envelope radius ${maximumRadius.toFixed(2)}m`);
}
await writeFile(`${out}/integrity.json`,JSON.stringify({status:'pass',note:'Offline geometry/animation checks only; no production visual acceptance claimed',rows},null,2)+'\n');
