import sharp from 'sharp';import fs from 'node:fs';import path from 'node:path';import * as THREE from 'three';
const source=JSON.parse(fs.readFileSync(new URL('./derived/source.json',import.meta.url),'utf8'));
const root=path.resolve('tools/rpg-bestiary/roach-source/derived');
const derived=path.resolve('tools/rpg-bestiary/roach-source/derived');
// Blender UVs use bottom-origin V; glTF decoded texture rows use top-origin. Flip image rows, retaining source UV/tangent orientation.
await sharp(path.join(root,'Roach.png')).flip().png().toFile(path.join(derived,'source-color-gltf.png'));
const normal=await sharp(path.join(root,'RoachNormal.png')).flip().raw().toBuffer({resolveWithObject:true});for(let i=0;i<normal.data.length;i+=normal.info.channels){let x=(normal.data[i]/127.5-1)*.125,y=(normal.data[i+1]/127.5-1)*.125,z=normal.data[i+2]/127.5-1;const len=Math.hypot(x,y,z)||1;normal.data[i]=Math.round((x/len+1)*127.5);normal.data[i+1]=Math.round((y/len+1)*127.5);normal.data[i+2]=Math.round((z/len+1)*127.5);}await sharp(normal.data,{raw:normal.info}).png().toFile(path.join(derived,'source-normal-gltf.png'));
export function buildRoach(id='cave_roach'){
 const object=new THREE.Group();object.name=id;const motion=new THREE.Group();motion.name='roach_source_ground';object.add(motion);
 const jointIds=new Set(source.meshes.flatMap(m=>m.joints));const nodes=source.nodes.map(n=>{const o=jointIds.has(n.id)?new THREE.Bone():new THREE.Group();o.name=`roach_${n.id}_${n.name.replace(/[^a-zA-Z0-9_]/g,'_')}`;o.position.fromArray(n.position);o.quaternion.fromArray(n.quaternion);o.scale.fromArray(n.scale);return o;});
 for(const n of source.nodes){if(n.parent===null)motion.add(nodes[n.id]);else nodes[n.parent].add(nodes[n.id]);}object.updateMatrixWorld(true);
 const material=new THREE.MeshStandardMaterial({name:'roach_original_rock',color:0xffffff,roughness:.65,metalness:0,side:THREE.DoubleSide});
 for(const m of source.meshes){const geometry=new THREE.BufferGeometry();for(const [key,name,size,C]of [['positions','position',3,Float32Array],['normals','normal',3,Float32Array],['uvs','uv',2,Float32Array],['skinIndices','skinIndex',4,Uint16Array],['skinWeights','skinWeight',4,Float32Array]])geometry.setAttribute(name,new THREE.BufferAttribute(new C(m[key]),size));
  geometry.computeBoundingBox();const skeleton=new THREE.Skeleton(m.joints.map(i=>nodes[i]),m.inverseBindMatrices.map(a=>new THREE.Matrix4().fromArray(a)));const mesh=new THREE.SkinnedMesh(geometry,material);mesh.name='roach_original_body';mesh.frustumCulled=false;mesh.castShadow=true;mesh.receiveShadow=true;motion.add(mesh);mesh.bind(skeleton,new THREE.Matrix4());mesh._sourceFullWeights=m.fullWeights;
 }
 const mapping={Idle:'Idle',Walk:'Walk',Run:'Flee',Attack:'Attack1',AttackSecondary:'Attack2',Hit:'Idle',HitLeft:'Idle',HitRight:'Idle',Death:'Die'};
 const clips=Object.entries(mapping).map(([name,original])=>{const a=source.clips.find(c=>c.name===original),tracks=[],isHit=name.startsWith('Hit');const selected=a.times.map((t,i)=>[t,i]).filter(([t])=>!isHit||t<=.42),times=selected.map(([t])=>t);for(const t of a.tracks)for(const [property,size,Type]of [['position',3,THREE.VectorKeyframeTrack],['quaternion',4,THREE.QuaternionKeyframeTrack],['scale',3,THREE.VectorKeyframeTrack]]){const values=selected.flatMap(([,i])=>t[property].slice(i*size,i*size+size));if(isHit&&property==='quaternion'&&t.node===2){for(let i=0;i<times.length;i++){const pulse=Math.sin(Math.PI*times[i]/times.at(-1)),q=new THREE.Quaternion().fromArray(values,i*4);q.multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(-.16*pulse,(name==='HitLeft'?1:name==='HitRight'?-1:0)*.18*pulse,0))).toArray(values,i*4);}}if(values.every((v,i)=>Math.abs(v-values[i%size])<1e-8)&&nodes[t.node][property].toArray().every((v,i)=>Math.abs(v-values[i])<1e-8))continue;tracks.push(new Type(`${nodes[t.node].name}.${property}`,times,values));}return new THREE.AnimationClip(name,times.at(-1),tracks);});
 object.animations=clips;object.updateMatrixWorld(true);const mixer=new THREE.AnimationMixer(object);mixer.clipAction(clips[0]).play();mixer.setTime(0);object.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(object,true);const scale=1.15/box.getSize(new THREE.Vector3()).y;object.scale.setScalar(scale);object.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(object,true);object.position.y=-box.min.y;mixer.stopAllAction();object.updateMatrixWorld(true);
 const floorCorrection={};
 for(const clip of clips){const action=mixer.clipAction(clip);action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.play();const sampleSet=new Set([0,clip.duration]);for(let t=0;t<clip.duration;t+=1/60)sampleSet.add(t);for(const track of clip.tracks)for(const t of track.times)sampleSet.add(t);const times=[],values=[];let maximumLift=0;
  for(const time of [...sampleSet].sort((a,b)=>a-b)){mixer.setTime(time);object.updateMatrixWorld(true);const floor=new THREE.Box3().setFromObject(object,true).min.y,lift=Math.max(0,.005-floor);times.push(time);values.push(0,lift/scale,0);maximumLift=Math.max(maximumLift,lift);}action.stop();mixer.uncacheClip(clip);clip.tracks.push(new THREE.VectorKeyframeTrack('roach_source_ground.position',times,values));floorCorrection[clip.name]={samples:times.length,maximumLift};
 }mixer.stopAllAction();object.updateMatrixWorld(true);
 const meta={family:'roach',height:1.15,rig:'original-roach-54-bone',source:'Roach by Atmostatic; rig, animation and retexture by Danimal',license:'CC-BY-SA-3.0',floorCorrection,sourceFacts:source.sourceFacts,provenance:{url:'https://opengameart.org/content/roach-game-ready-and-animated',author:'Atmostatic',animator:'Danimal',license:'CC-BY-SA-3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',attribution:'Roach, original model by Atmostatic https://opengameart.org/users/atmostatic; rig, animation and retexture by Danimal https://opengameart.org/users/danimal. CC BY-SA 3.0, OGA https://opengameart.org/content/roach-game-ready-and-animated. Converted asset and its documented adaptations retain CC BY-SA 3.0.',sourceFiles:source.sourceFiles,modifications:'Original body and all54bones preserved without weight reduction. Native NLA timings sampled at48Hz; Blender Z-up to glTF Y-up, 1.15m normalization, floor correction. Missing Hit reactions derive from native Idle with an authored SpineHigh recoil. No grafts or body edits.',weightReduction:source.weightReduction,materialConversion:{sourceNormalStrength:.125,sourceSpecularIntensity:.02127659320831299,sourceHardness:50,sourceSpecularPath:path.join(derived,'Roach-Spec.png'),roughness:.65,roughnessMeaning:'Constant preview roughness, not derived from specular intensity; original specular map retained for future explicit channel support',normalMeaning:'Original tangent normal image with original normal strength0.125 baked into XY and renormalized; image rows adapted to glTF',evidence:'test-results/roach-source/legacy-material-slots.json'}},textureBindings:[{materialName:material.name,baseColorPath:path.join(derived,'source-color-gltf.png'),normalPath:path.join(derived,'source-normal-gltf.png'),flipY:false}],clipProvenance:Object.entries(mapping).map(([name,original])=>({name,source:original,...Object.fromEntries(['action','firstFrame','lastFrame','timelineStart','timelineEnd','fps','sampleFps'].map(k=>[k,source.clips.find(c=>c.name===original)[k]])),derivation:name.startsWith('Hit')?'Native Idle first0.4167s plus authored SpineHigh pitch recoil; directional yaw for HitLeft/HitRight. No native Hit exists':name==='Run'?'Original source Flee NLA timing, using source Walk action at its authored faster playback':'Native source NLA strip'})),sourceAnimationCount:source.clips.length,attackContact:.5,animationAcceptance:'candidate-needs-production-browser-review',revision:'roach-source-1'};
 return {object,clips,meta};
}


