import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import * as T from 'three';
import {loadForestSource} from './source-glb.mjs';

const dir=path.resolve('tools/rpg-bestiary/forest-monster-source/derived');
const hash=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
export const forestProvenance={author:'Čestmír Dammer (CDmir); texture derivation Rick Hoppmann; concept Torben',license:'CC0-1.0',source:'https://opengameart.org/content/forest-monster',sourceAssets:['forest-monster-final.blend','Monster','Tree'],sourcePacks:[{id:'forest-monster-current',author:'Čestmír Dammer (CDmir)',license:'CC0-1.0',source:'https://opengameart.org/content/forest-monster',download:'https://opengameart.org/sites/default/files/forest-monster_0.7z',sha256:'3378edfe2441d1cee93feeeb6e045b9ff0c700d85b398dfa6c29c83f7e696a5e'}],sourceRecords:[{archive:'forest-monster_0.7z',sha256:'3378edfe2441d1cee93feeeb6e045b9ff0c700d85b398dfa6c29c83f7e696a5e',licenseFile:'tools/rpg-bestiary/forest-monster-source/Licenses.txt',licenseEvidence:'Current archive says CC0; official author 2015-09-03 comment confirms former restricted tree texture replaced and all current contents CC0'}],modifications:'Complete authored Monster and Tree meshes with original 76-bone rig; Blender constraint animation baked to glTF; no topology additions, grafts or anatomy edits; uniform source-units conversion to meters; original current-archive diffuse/normal/AO/specular texture channels; Walk-tempo Run and Melee_Hold-derived directional hit clips; whole-mesh ground alignment; native takes contain no authored aerial locomotion'};

export function buildForestMonster(id='forest_monster'){
  const base=loadForestSource(path.join(dir,'Idle.glb'));
  // Original MATree diffuse slot mapto=129 binds both color (1) and alpha (128).
  // The packed RGBA PNG contains leaf cutouts; Blender conversion omitted this binding.
  for(const mat of base.materials)if(mat.name.endsWith('_Tree')){mat.alphaTest=.5;mat.transparent=false;mat.opacity=1;mat.needsUpdate=true;}
  const sourceAlpha={material:'Tree',mode:'MASK',cutoff:.5,channel:'baseColorTexture.a',textureSha256:hash(path.join(dir,'tree.png')),sourceConvention:'Original MATree diffuse MTex mapto129 = color1 + alpha128; alphafac1. PNG has102618 fully transparent texels and42145 partial-alpha texels.',translation:'Source alpha translated to production cutout threshold0.5; threshold is a runtime choice, not claimed as an original Blender value.',evidence:'test-results/forest-alpha-repair/alpha-evidence.json',textureBytesModified:false};
  const object=new T.Group();object.name=id;const motion=new T.Group();motion.name='forest_ground_motion';object.add(motion);base.object.name='forest_authored_model';base.object.scale.setScalar(.1);motion.add(base.object);
  // Original Blender 2.75 MTex slots bind diffuse, normal and specular only.
  // The archive AO image is an unused source image, not an active occlusion map.
  const textureBindings=base.materials.map(mat=>{const tree=mat.name.endsWith('_Tree'),prefix=tree?'tree':'forest-monster';return {materialName:mat.name,baseColorPath:path.join(dir,tree?'tree.png':'forest-monster-skin1.png'),normalPath:path.join(dir,`${prefix}-norm.png`),specularPath:path.join(dir,`${prefix}-spec.png`),flipY:false};});
  const sourceOcclusion={aoPath:path.join(dir,'forest-monster-AO.png'),sha256:hash(path.join(dir,'forest-monster-AO.png')),active:false,reason:'Original Blender 2.75 Material/MTex pointers contain no AO binding. Monster has only diffuse, normal and specular slots. The AO image is retained from the current archive as unused source data; no runtime occlusion binding or inferred strength is added.',evidence:'test-results/forest-monster-source/legacy-material-slots.json',inspectionMethod:'Direct original-file SDNA decode with inspect_legacy_ao.mjs'};
  const native={Idle:base.clips[0]};for(const name of ['Walk','Melee_Hold','Attack','Dying']){const s=loadForestSource(path.join(dir,`${name}.glb`));const names=s.nodes.map(n=>n.name);if(JSON.stringify(names)!==JSON.stringify(base.nodes.map(n=>n.name)))throw new Error(`Native take changed node identities: ${name}`);native[name]=s.clips[0];}
  const clone=(src,name,speed=1)=>{const c=native[src].clone();c.name=name;if(speed!==1){for(const t of c.tracks)for(let i=0;i<t.times.length;i++)t.times[i]/=speed;c.duration/=speed;}return c;};
  const clips=[clone('Idle','Idle'),clone('Walk','Walk'),clone('Walk','Run',1.45),clone('Attack','Attack')];
  for(const name of ['Hit','HitLeft','HitRight']){const clip=clone('Melee_Hold',name,native.Melee_Hold.duration/.6);const track=clip.tracks.find(t=>/Spine2.quaternion$/.test(t.name));if(!track)throw new Error('Missing native Spine2');for(let i=0;i<track.times.length;i++){const phase=track.times[i]/clip.duration,q=new T.Quaternion().fromArray(track.values,i*4),amount=Math.sin(phase*Math.PI);q.multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),-.10*amount));if(name!=='Hit')q.multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),(name==='HitLeft'?1:-1)*.16*amount));q.toArray(track.values,i*4);}clips.push(clip);}
  clips.push(clone('Dying','Death'));
  function bounds(){object.updateMatrixWorld(true);const box=new T.Box3();object.traverse(n=>{if(!n.isMesh)return;if(n.isSkinnedMesh)n.skeleton.update();for(let i=0;i<n.geometry.attributes.position.count;i++){const p=new T.Vector3().fromBufferAttribute(n.geometry.attributes.position,i);if(n.isSkinnedMesh)n.applyBoneTransform(i,p);p.applyMatrix4(n.matrixWorld);if(!Number.isFinite(p.x+p.y+p.z))throw new Error(`Nonfinite ${n.name} vertex ${i}`);box.expandByPoint(p);}});return box;}
  const rest=bounds();motion.position.y=-rest.min.y;const animationFloorChecks=[];
  for(const clip of clips){const mixer=new T.AnimationMixer(object),a=mixer.clipAction(clip);a.setLoop(T.LoopOnce,1);a.clampWhenFinished=true;a.play();const times=[],positions=[],count=Math.ceil(clip.duration*60);let rawMin=Infinity,maxLift=0;
    for(let i=0;i<=count;i++){const time=clip.duration*i/count;mixer.setTime(time);const y=bounds().min.y,lift=.003-y;rawMin=Math.min(rawMin,y);maxLift=Math.max(maxLift,lift);times.push(time);positions.push(0,motion.position.y+lift,0);}
    a.stop();mixer.uncacheRoot(object);clip.tracks.push(new T.VectorKeyframeTrack(`${motion.name}.position`,times,positions));animationFloorChecks.push({clip:clip.name,rawMinFloor:rawMin,maximumLift:maxLift});
  }
  for(const clip of clips){const mixer=new T.AnimationMixer(object),a=mixer.clipAction(clip);a.setLoop(T.LoopOnce,1);a.clampWhenFinished=true;a.play();let min=Infinity,max=-Infinity;const first=[];for(let i=0;i<=32;i++){mixer.setTime(clip.duration*i/32);const b=bounds();min=Math.min(min,b.min.y);max=Math.max(max,b.max.y);if(i===0)first.push(...b.min.toArray(),...b.max.toArray());}a.stop();mixer.uncacheRoot(object);Object.assign(animationFloorChecks.find(c=>c.clip===clip.name),{minFloor:min,maxHeight:max,firstBounds:first});}
  const size=bounds().getSize(new T.Vector3());let meshCount=0,vertices=0,triangles=0;object.traverse(n=>{if(n.isMesh){meshCount++;vertices+=n.geometry.attributes.position.count;triangles+=(n.geometry.index?.count??n.geometry.attributes.position.count)/3;}});
  const clipSources={Idle:{take:'Idle',frames:[0,190]},Walk:{take:'Walk',frames:[0,40]},Run:{take:'Walk',frames:[0,40],derivative:'1.45x native Walk tempo; no authored running take'},Attack:{take:'Attack',frames:[0,30],contactFrames:[10,15]},Hit:{take:'Melee_Hold',frames:[0,50],derivative:'compressed to 0.6s with 0.10rad Spine2 recoil'},HitLeft:{take:'Melee_Hold',frames:[0,50],derivative:'same recoil plus +0.16rad directional Spine2 turn'},HitRight:{take:'Melee_Hold',frames:[0,50],derivative:'same recoil plus -0.16rad directional Spine2 turn'},Death:{take:'Dying',frames:[0,35]}};
  return {object,clips,meta:{id,family:'forest_monster',revision:'forest-monster-source-review-1',height:size.y,dimensions:size.toArray(),rig:'authored-76-bone-forest-monster',meshCount,vertices,triangles,attackContact:12/30,attackContactSource:'Author Licenses.txt marks native strike frames10–15 of30; midpoint12 used',source:forestProvenance.source,license:forestProvenance.license,provenance:forestProvenance,textureBindings,sourceOcclusion,sourceAlpha,textureChannels:textureBindings.map(b=>Object.fromEntries(Object.entries(b).map(([k,v])=>[k,k.endsWith('Path')?{path:v,sha256:hash(v)}:v]))),clipSources,animationFloorChecks,exportNotes:'Blender4.5.11 forced sampling preserves evaluated source constraints; source vertices with >4 weights reduced to top4 and renormalized for production glTF path',approval:'candidate-awaiting-production-browser-review'}};
}


