"""Wrapper-only normalization for provisional source selection, no geometry changes."""
import pathlib,json,struct,hashlib
root=pathlib.Path(__file__).resolve().parent
source=root/'gonsplitters-badger-source-preview.glb';raw=source.read_bytes();size=struct.unpack_from('<I',raw,12)[0];doc=json.loads(raw[20:20+size]);tail=raw[20+size:]
validation=json.loads((root/'gonsplitters-preview-validation.json').read_text());bounds=validation['worldBounds'];lo=bounds['min'];hi=bounds['max'];scale=.35/(hi[1]-lo[1])
translation=[-(lo[0]+hi[0])*.5*scale,-lo[1]*scale,-(lo[2]+hi[2])*.5*scale]
scene=doc['scenes'][doc.get('scene',0)];children=scene['nodes'][:];scene['nodes']=[len(doc['nodes'])];doc['nodes'].append({'name':'Provisional_badger_source_grounded_wrapper','children':children,'translation':translation,'scale':[scale]*3})
encoded=json.dumps(doc,separators=(',',':')).encode();encoded+=b' '*((-len(encoded))%4)
target=root/'gonsplitters-badger-preview-normalized.glb';target.write_bytes(struct.pack('<III',0x46546c67,2,20+len(encoded)+len(tail))+struct.pack('<II',len(encoded),0x4e4f534a)+encoded+tail)
minima=[lo[a]*scale+translation[a] for a in range(3)];maxima=[hi[a]*scale+translation[a] for a in range(3)];dimensions=[maxima[a]-minima[a] for a in range(3)]
provenance={'author':'Miguel Zavala (mz4250), mesh attributed by Gonsplitters; texture/package Gonsplitters','source':'https://thunderstore.io/c/talespire/p/Gonsplitters/Gonsplitters_Beasts_Collection/','download':'https://thunderstore.io/package/download/Gonsplitters/Gonsplitters_Beasts_Collection/1.0.3/','license':'CC-BY-SA-4.0 declared by redistribution publisher; exact original creator grant UNVERIFIED','licenseUrl':'https://creativecommons.org/licenses/by-sa/4.0/','originalCreatorPage':'https://thangs.com/designer/mz4250/3d-model/Badger-18694','originalCreatorLicenseVerified':False,'commercialClearance':'provisional, do not publish as cleared','sourceSha256':'ef00545e513c4b3008947418b784f22288cc9a654234591bda456fd1a94f0e86','rawPreviewSha256':hashlib.sha256(raw).hexdigest(),'sourceNativeActions':[],'adaptationPerformed':False}
asset={'id':'creature_rootdelve_badger','file':'models/creature/creature_rootdelve_badger.glb','pack':'gonsplitters-badger-provisional-source-review','category':'character','is':'complete original Badger static source review; PROVISIONAL RIGHTS: publisher declares CC-BY-SA4, exact original creator grant unverified','tags':['badger','original-source','whole-body-evaluation','static-preview','provisional-rights'],'bytes':target.stat().st_size,'sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'size':dict(zip('xyz',dimensions)),'base':dict(zip('xyz',minima)),'bounds':{'min':minima,'max':maxima},'groundY':minima[1],'triangles':49976,'animations':[],'materials':['Source_Unity_Standard_translated'],'sourceProvenance':provenance,'acceptance':{'sourceMeasured':True,'labAccepted':False,'worldIntegrated':False,'originalCreatorGrantVerified':False}}
catalogue={'schema':1,'scope':'Provisional Badger source review only; no runtime or licensing acceptance.','assets':[asset],'packs':[{'id':asset['pack'],'name':'Gonsplitters Badger provisional rights source review','author':provenance['author'],'source':provenance['source'],'license':provenance['license']}],'files':{asset['id']:target.name},'previewTransform':{'scale':scale,'translation':translation,'rotation':'identity; original facial white-mask UV samples lie at +Z end, nose points generally +Z in original authored pose','targetHeight':.35,'units':'Authored .35m overall source height, approximately shoulder height for this posed source; not measured zoological dimensions.','rawBounds':bounds,'geometryAndTexturesUnchanged':True,'binaryChunkSha256':hashlib.sha256(tail).hexdigest()},'floorAndAxisLimits':['Grounded minimum rest vertex at zero; does not prove each paw contact.','No bones, weights or animation clips exist in this source.','Original posed body, mesh topology and materials require hardware full-body review, especially feet.','No original creator grant verified. Publisher CC-BY-SA4 declaration retained; do not promote to cleared public assets.','Unity parallax height cannot be translated directly to standard GLTF and is omitted.']}
(root/'candidate-catalogue.json').write_text(json.dumps(catalogue,indent=2));print(json.dumps({'file':target.name,'sha256':asset['sha256'],'bytes':asset['bytes'],'size':asset['size'],'scale':scale,'translation':translation}))
