/**
 * Rebuild the close-fitting Starhide hand shell from the production body.
 * Run: npx tsx tools/item-models/starhide/wrap-extract-hand.ts
 * Add --check to compare the generated bytes without changing accepted data.
 */
import { NodeIO } from '@gltf-transform/core';
import { readFileSync, writeFileSync } from 'node:fs';

interface Vertex {
  p: number[];
  n: number[];
  uv: number[];
}

const source = 'game/public/assets/models/character/base_male.glb';
const destination = 'tools/item-models/starhide/wrap-hand-data.json';
const sourceMesh = 'SuperHero_Male';
const cuffPlane = 0.694;
const surfaceOffset = 0.0018;
const uvScale = 14;
const document = await new NodeIO().read(source);
const mesh = document.getRoot().listNodes()
  .find((node) => node.getName() === sourceMesh)?.getMesh();
if (!mesh) throw new Error('Native male body is missing');

const positions: number[] = [];
const normals: number[] = [];
const uvs: number[] = [];
const indices: number[] = [];
const cache = new Map<string, number>();
const rounded = (value: number): number => Math.round(value * 1e8) / 1e8;

function addVertex(vertex: Vertex): number {
  const key = [...vertex.p, ...vertex.n, ...vertex.uv].map(rounded).join(',');
  const existing = cache.get(key);
  if (existing !== undefined) return existing;
  const index = positions.length / 3;
  positions.push(...vertex.p.map(rounded));
  normals.push(...vertex.n.map(rounded));
  uvs.push(...vertex.uv.map((value) => rounded(value * uvScale)));
  cache.set(key, index);
  return index;
}

function intersection(a: Vertex, b: Vertex): Vertex {
  const t = (cuffPlane - a.p[0]!) / (b.p[0]! - a.p[0]!);
  const p = a.p.map((value, i) => value + (b.p[i]! - value) * t);
  p[0] = cuffPlane;
  const n = a.n.map((value, i) => value + (b.n[i]! - value) * t);
  const length = Math.hypot(...n);
  for (let i = 0; i < 3; i++) n[i] = n[i]! / length;
  const uv = a.uv.map((value, i) => value + (b.uv[i]! - value) * t);
  return { p, n, uv };
}

for (const primitive of mesh.listPrimitives()) {
  const p = primitive.getAttribute('POSITION');
  const n = primitive.getAttribute('NORMAL');
  const uv = primitive.getAttribute('TEXCOORD_0');
  const index = primitive.getIndices();
  if (!p || !n || !uv || !index) throw new Error('Native body attributes are incomplete');

  // Offset first, then clip, so the finished cuff edge stays on its exact plane.
  const vertices: Vertex[] = Array.from({ length: p.getCount() }, (_, i) => {
    const a: number[] = [], b: number[] = [], c: number[] = [];
    p.getElement(i, a);
    n.getElement(i, b);
    uv.getElement(i, c);
    const length = Math.hypot(...b);
    for (let j = 0; j < 3; j++) {
      b[j] = b[j]! / length;
      a[j] = a[j]! + b[j]! * surfaceOffset;
    }
    return { p: a, n: b, uv: c };
  });

  for (let i = 0; i < index.getCount(); i += 3) {
    const triangle = [
      vertices[index.getScalar(i)]!,
      vertices[index.getScalar(i + 1)]!,
      vertices[index.getScalar(i + 2)]!,
    ];
    const polygon: Vertex[] = [];
    for (let j = 0; j < 3; j++) {
      const a = triangle[j]!, b = triangle[(j + 1) % 3]!;
      const insideA = a.p[0]! >= cuffPlane, insideB = b.p[0]! >= cuffPlane;
      if (insideA) polygon.push(a);
      if (insideA !== insideB) polygon.push(intersection(a, b));
    }
    for (let j = 1; j < polygon.length - 1; j++) {
      const a = polygon[0]!.p, b = polygon[j]!.p, c = polygon[j + 1]!.p;
      const ab = b.map((value, k) => value - a[k]!);
      const ac = c.map((value, k) => value - a[k]!);
      const area = Math.hypot(
        ab[1]! * ac[2]! - ab[2]! * ac[1]!,
        ab[2]! * ac[0]! - ab[0]! * ac[2]!,
        ab[0]! * ac[1]! - ab[1]! * ac[0]!,
      );
      if (area < 1e-12) continue;
      indices.push(addVertex(polygon[0]!), addVertex(polygon[j]!), addVertex(polygon[j + 1]!));
    }
  }
}

if (!positions.length || [...positions, ...normals, ...uvs].some((value) => !Number.isFinite(value))) {
  throw new Error('Non-finite or empty hand shell');
}

// Very tight finger creases can invert under the normal offset. Retain their
// geometry while orienting their triangles to the native outward normals.
let offsetFoldWindingRepairs = 0;
for (let i = 0; i < indices.length; i += 3) {
  const ids = indices.slice(i, i + 3);
  const p = ids.map((id) => positions.slice(id * 3, id * 3 + 3));
  const normal = [0, 0, 0];
  for (const id of ids) {
    for (let j = 0; j < 3; j++) normal[j] = normal[j]! + normals[id * 3 + j]!;
  }
  const a = p[1]!.map((value, j) => value - p[0]![j]!);
  const b = p[2]!.map((value, j) => value - p[0]![j]!);
  const cross = [
    a[1]! * b[2]! - a[2]! * b[1]!,
    a[2]! * b[0]! - a[0]! * b[2]!,
    a[0]! * b[1]! - a[1]! * b[0]!,
  ];
  if (cross.reduce((sum, value, j) => sum + value * normal[j]!, 0) < 0) {
    [indices[i + 1], indices[i + 2]] = [indices[i + 2]!, indices[i + 1]!];
    offsetFoldWindingRepairs++;
  }
}

const data = {
  source, sourceMesh, cuffPlane, surfaceOffset, uvScale,
  positions, normals, uvs, indices, offsetFoldWindingRepairs,
};
const output = JSON.stringify(data) + '\n';
if (process.argv.includes('--check')) {
  if (readFileSync(destination, 'utf8') !== output) {
    throw new Error('Generated hand shell differs from the accepted data');
  }
} else {
  writeFileSync(destination, output);
}
console.log(JSON.stringify({
  destination,
  verifiedOnly: process.argv.includes('--check'),
  vertices: positions.length / 3,
  triangles: indices.length / 3,
  offsetFoldWindingRepairs,
  bytes: Buffer.byteLength(output),
}));
