import * as T from 'three';
/** CPU skin evaluation of every indexed vertex. Uses the same joint * inverse-bind equation as glTF. */
export function measureAndGround(doc,id,{hover=false}={}){
 const root=doc.getRoot(),buffer=root.listBuffers()[0],scenes=root.listScenes();
 const wrapper=doc.createNode(`${id}_authored_ground`);for(const scene of scenes){for(const child of scene.listChildren()){scene.removeChild(child);wrapper.addChild(child);}scene.addChild(wrapper);}
 const nodes=root.listNodes(),rests=new Map(nodes.map(n=>[n,{t:n.getTranslation(),q:n.getRotation(),s:n.getScale()}]));
 const draws=[];for(const node of nodes){if(!node.getMesh())continue;const skin=node.getSkin(),joints=skin?.listJoints(),inverse=skin?.getInverseBindMatrices()?.getArray();for(const primitive of node.getMesh().listPrimitives()){const p=primitive.getAttribute('POSITION').getArray(),si=primitive.getAttribute('JOINTS_0')?.getArray(),sw=primitive.getAttribute('WEIGHTS_0')?.getArray(),ids=[...new Set(primitive.getIndices()?.getArray()??Array.from({length:p.length/3},(_,i)=>i))];draws.push({node,p,si,sw,ids,joints,inverses:joints?.map((_,i)=>new T.Matrix4().fromArray(inverse,i*16))});}}
 const clips=root.listAnimations().map(a=>({a,name:a.getName(),duration:Math.max(...a.listSamplers().flatMap(s=>[...s.getInput().getArray()])),channels:a.listChannels().map(c=>({node:c.getTargetNode(),path:c.getTargetPath(),times:c.getSampler().getInput().getArray(),values:c.getSampler().getOutput().getArray(),interpolation:c.getSampler().getInterpolation()}))}));
 function reset(){for(const [n,r]of rests)n.setTranslation(r.t).setRotation(r.q).setScale(r.s);}
 function pose(clip,t){for(const c of clip.channels){let hi=0;while(hi<c.times.length-1&&c.times[hi]<t)hi++;const lo=Math.max(0,hi-1),dt=c.times[hi]-c.times[lo],f=c.interpolation==='STEP'||dt<=0?0:Math.max(0,Math.min(1,(t-c.times[lo])/dt));if(c.path==='rotation'){const a=new T.Quaternion().fromArray(c.values,lo*4),b=new T.Quaternion().fromArray(c.values,hi*4);c.node.setRotation(a.slerp(b,f).toArray());}else{const value=[0,1,2].map(k=>c.values[lo*3+k]+(c.values[hi*3+k]-c.values[lo*3+k])*f);if(c.path==='translation')c.node.setTranslation(value);else if(c.path==='scale')c.node.setScale(value);}}}
 function bounds(){const box=new T.Box3(),worlds=new Map(nodes.map(n=>[n,new T.Matrix4().fromArray(n.getWorldMatrix())])),v=new T.Vector3(),p=new T.Vector3(),sum=new T.Vector3();for(const d of draws){const matrices=d.joints?.map((j,i)=>worlds.get(j).clone().multiply(d.inverses[i]));for(const i of d.ids){v.fromArray(d.p,i*3);if(matrices&&d.si&&d.sw){sum.set(0,0,0);for(let k=0;k<4;k++){const weight=d.sw[i*4+k];if(weight)sum.addScaledVector(p.copy(v).applyMatrix4(matrices[d.si[i*4+k]]),weight);}v.copy(sum);}else v.applyMatrix4(worlds.get(d.node));if(!Number.isFinite(v.x+v.y+v.z))throw new Error(`Non-finite skin in ${id}`);box.expandByPoint(v);}}return {min:box.min.toArray(),max:box.max.toArray()};}
 const reports=[];let minFloor=Infinity;let idleBounds;
 for(const c of clips){reset();const count=Math.max(48,Math.ceil(c.duration*24)),times=[],translations=[],frameBounds=[];let maxLift=0,minRaw=Infinity,maxRaw=-Infinity;
  for(let i=0;i<=count;i++){const t=c.duration*i/count;pose(c,t);wrapper.setTranslation([0,0,0]);const b=bounds(),target=hover&&c.name!=='Death'?.10+.024*Math.sin(i/count*Math.PI*2):.003;const lift=hover||c.name==='Death'?target-b.min[1]:Math.max(0,target-b.min[1]);maxLift=Math.max(maxLift,Math.abs(lift));minRaw=Math.min(minRaw,b.min[1]);maxRaw=Math.max(maxRaw,b.min[1]);times.push(t);translations.push(0,lift,0);frameBounds.push({min:b.min.map((v,k)=>v+(k===1?lift:0)),max:b.max.map((v,k)=>v+(k===1?lift:0))});minFloor=Math.min(minFloor,b.min[1]+lift);}
  if(c.name==='Idle')idleBounds=frameBounds[0];
  const input=doc.createAccessor().setType('SCALAR').setArray(Float32Array.from(times)).setBuffer(buffer),output=doc.createAccessor().setType('VEC3').setArray(Float32Array.from(translations)).setBuffer(buffer),sampler=doc.createAnimationSampler().setInput(input).setOutput(output).setInterpolation('LINEAR');c.a.addSampler(sampler).addChannel(doc.createAnimationChannel().setTargetNode(wrapper).setTargetPath('translation').setSampler(sampler));
  reports.push({clip:c.name,samples:count+1,duration:c.duration,rawFloor:[minRaw,maxRaw],maxCorrection:maxLift,bounds:{min:[0,1,2].map(k=>Math.min(...frameBounds.map(b=>b.min[k]))),max:[0,1,2].map(k=>Math.max(...frameBounds.map(b=>b.max[k])))}});
 }
 reset();const idle=clips.find(c=>c.name==='Idle');if(idle){pose(idle,0);const raw=bounds();wrapper.setTranslation([0,(hover?.10:.003)-raw.min[1],0]);}
 return {method:'All indexed vertices; native joint world matrices multiplied by inverse bind matrices, sampled at >=24Hz. Ground correction is an authored root channel.',idleBounds,minFloor,clips:reports};
}
