import * as THREE from 'three';
import type { ItemModelAuthor } from '../contracts';

const TAU=Math.PI*2;
const V=(x:number,y:number,z:number)=>new THREE.Vector3(x,y,z);
function mesh(name:string,g:THREE.BufferGeometry,m:THREE.Material){g.name=name+' geometry';const o=new THREE.Mesh(g,m);o.name=name;return o;}
function texture(name:string,fn:(x:number,y:number)=>number[],color=false){const n=256,d=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const c=fn(x/n,y/n),i=(y*n+x)*4;for(let k=0;k<3;k++)d[i+k]=Math.round(Math.max(0,Math.min(255,c[k]!)));d[i+3]=255;}const t=new THREE.DataTexture(d,n,n,THREE.RGBAFormat);t.name=name;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.magFilter=THREE.LinearFilter;t.minFilter=THREE.LinearMipmapLinearFilter;t.generateMipmaps=true;if(color)t.colorSpace=THREE.SRGBColorSpace;t.needsUpdate=true;return t;}
const noise=(x:number,y:number)=>Math.sin(x*391.7+y*184.1)*Math.sin(x*173.3-y*271.9);
function metal(name:string,color:number,rough:number){
  const height=(x:number,y:number)=>{let h=0;for(let k=0;k<29;k++){const cx=(k*.618033)%1,cy=(k*.414214)%1;const dx=Math.sin(Math.PI*(x-cx))/Math.PI,dy=Math.sin(Math.PI*(y-cy))/Math.PI;h-=.012*Math.exp(-(dx*dx+dy*dy)/.0017);}return h;};
  return new THREE.MeshStandardMaterial({name,color,metalness:.92,roughness:rough,map:texture(name+' subtle annealing color',(x,y)=>{const q=241+8*noise(x,y);return[q,q,q];},true),roughnessMap:texture(name+' independent polish',(x,y)=>{const q=215+22*Math.sin(x*23+y*11)*Math.cos(y*31);return[q,q,255];}),normalMap:texture(name+' smooth hammer depression normals',(x,y)=>{const e=1/128,n=V(-(height(x+e,y)-height(x-e,y))/(2*e),-(height(x,y+e)-height(x,y-e))/(2*e),1).normalize();return[(n.x*.5+.5)*255,(n.y*.5+.5)*255,(n.z*.5+.5)*255];})});
}
/** A comfort bore remains circular; the external section is separately sculpted. */
function band(width:number,thick:number,kind:'silver'|'cinder'|'night',material:THREE.Material){const p:number[]=[],uv:number[]=[],ix:number[]=[];const n=192,s=kind==='cinder'?64:24;for(let i=0;i<=n;i++){const a=i/n*TAU,top=Math.pow(Math.max(0,Math.sin(a)),6);for(let j=0;j<=s;j++){const t=j/s*TAU,c=Math.sign(Math.cos(t))*Math.pow(Math.abs(Math.cos(t)),.32),z=Math.sign(Math.sin(t))*Math.pow(Math.abs(Math.sin(t)),.32);let h=0;if(kind==='cinder'){for(let k=0;k<31;k++){const da=Math.atan2(Math.sin(a-k/31*TAU),Math.cos(a-k/31*TAU));h-=.00029*Math.exp(-Math.pow(da/.11,4)-Math.pow((z-Math.sin(k*2.4)*.65)/.6,2));}}if(kind==='cinder'){for(const side of[-1,1]){const dz=z*width/2-(side*.00215+.00038*Math.sin(a*5+.7)+.00018*Math.sin(a*11));h-=.00030*Math.exp(-Math.pow(dz/.00043,4));}}const r=.01+(thick+top*(kind==='silver'?.0004:.0008))*(c+1)/2+h*Math.pow((c+1)/2,3);p.push(r*Math.cos(a),r*Math.sin(a),z*(width+top*(kind==='silver'?.0012:0))/2);uv.push(i/n*4,j/s);}}for(let i=0;i<n;i++)for(let j=0;j<s;j++){const a=i*(s+1)+j,b=a+s+1;ix.push(a,b,a+1,a+1,b,b+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();return mesh(kind+' comfort bore forged band',g,material);}
function tube(name:string,points:THREE.Vector3[],r:number,m:THREE.Material,closed=false){return mesh(name,new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points,closed),Math.max(24,points.length*5),r,8,closed),m);}
/** Closed ridged polygon with narrow polished bevel and substantial side wall. */
function plaque(name:string,outline:number[][],depth:number,ridge:number,m:THREE.Material){const p:number[]=[],uv:number[]=[];const area=outline.reduce((sum,q,i)=>{const r=outline[(i+1)%outline.length]!;return sum+q[0]!*r[1]!-r[0]!*q[1]!;},0);if(area<0)outline=[...outline].reverse();const cx=outline.reduce((sum,q)=>sum+q[0]!,0)/outline.length,cy=outline.reduce((sum,q)=>sum+q[1]!,0)/outline.length;const n=outline.length;const verts=[...outline.map(q=>V(q[0]!,q[1]!,-depth/2)),...outline.map(q=>V(q[0]!,q[1]!,depth*.28)),...outline.map(q=>V(cx+(q[0]!-cx)*.92,cy+(q[1]!-cy)*.92,depth/2)),V(cx,cy,depth/2+ridge),V(cx,cy,-depth/2)];const tri=(a:number,b:number,c:number)=>{for(const k of[a,b,c]){const q=verts[k]!;p.push(q.x,q.y,q.z);uv.push(q.x/.02+.5,q.y/.03+.5);}};for(let i=0;i<n;i++){const j=(i+1)%n;tri(i,j,n+i);tri(j,n+j,n+i);tri(n+i,n+j,2*n+i);tri(n+j,2*n+j,2*n+i);tri(2*n+i,2*n+j,3*n);tri(j,i,3*n+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.computeVertexNormals();return mesh(name,g,m);}
function loop(name:string,x:number,y:number,z:number,rx:number,ry:number,r:number,m:THREE.Material,rotate=0){const o=tube(name,Array.from({length:24},(_,i)=>V(rx*Math.cos(i/24*TAU),ry*Math.sin(i/24*TAU),0)),r,m,true);o.rotation.y=rotate;o.position.set(x,y,z);return o;}
/** Folded tapering ribbon bail, with a narrow pointed toe and broad rolled crown. */
function bail(root:THREE.Group,m:THREE.Material,accent?:THREE.Material){
 const path=new THREE.CatmullRomCurve3([V(0,.0168,0),V(0,.0192,.0024),V(0,.0233,.0027),V(0,.025,.0002),V(0,.023,-.0024),V(0,.018,-.0015)],true);
 const ribbon=(name:string,material:THREE.Material,fraction:number,lift:number)=>{const p:number[]=[],uv:number[]=[],ix:number[]=[];const n=80,c=12;for(let i=0;i<=n;i++){const t=i/n,q=path.getPoint(t),dir=path.getTangent(t),normal=V(0,dir.z,-dir.y).normalize();const w=(.00085+.0018*Math.pow(Math.max(0,(q.y-.0168)/.0082),.7))*fraction;for(let j=0;j<=c;j++){const a=j/c*TAU,x=Math.sign(Math.cos(a))*Math.pow(Math.abs(Math.cos(a)),.35)*w,h=Math.sign(Math.sin(a))*Math.pow(Math.abs(Math.sin(a)),.55)*.00038+lift;const v=q.clone().add(V(x,0,0)).addScaledVector(normal,h);p.push(v.x,v.y,v.z);uv.push(t*2,j/c);}}for(let i=0;i<n;i++)for(let j=0;j<c;j++){const a=i*(c+1)+j,b=a+c+1;ix.push(a,a+1,b,a+1,b+1,b);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();root.add(mesh(name,g,material));};
 ribbon('Sculpted tapered folded bail',m,1,0);if(accent)ribbon('Hammered copper central bail inlay',accent,.3,.00005);
 root.add(loop('Closed articulated pendant connector',0,.0158,0,.00135,.0017,.00048,m));
}
/** Closed compact chain passes through the bail throat; every adjacent pair overlaps. */
function chain(root:THREE.Group,m:THREE.Material){const n=24;for(let i=0;i<n;i++){const a=i/n*TAU;const center=V(.006+.007*Math.sin(a),.015+.008*Math.cos(a),-.0015-.001*Math.sin(a));const tangent=V(.007*Math.cos(a),-.008*Math.sin(a),-.001*Math.cos(a)).normalize();const front=V(0,0,1),cross=tangent.clone().cross(front).normalize();const twist=i%2?Math.PI/2:0;const side=cross.multiplyScalar(Math.cos(twist)).addScaledVector(front,Math.sin(twist));const points=Array.from({length:20},(_,j)=>center.clone().addScaledVector(tangent,Math.cos(j/20*TAU)*.00165).addScaledVector(side,Math.sin(j/20*TAU)*.00105));root.add(tube('Interlinked closed cable chain '+i,points,.00042,m,true));}}
function emberMaterial(){const field=(x:number,y:number)=>Math.sin(x*15+Math.sin(y*19)*1.1)*Math.sin(y*13+Math.sin(x*23)*.9);const map=texture('Emberite internal amber fire and fine fracture color',(x,y)=>{const f=field(x,y),vein=Math.exp(-Math.abs(f)*40),speck=Math.pow(Math.max(0,noise(x*2,y*2)),12);const cloud=.5+.5*Math.sin(x*41+Math.sin(y*33)*3);return[228+27*cloud,55+90*cloud+100*vein+40*speck,5+16*cloud+20*vein];},true);return new THREE.MeshPhysicalMaterial({name:'Polished translucent fire amber emberite',color:0xffffff,map,roughness:.095,transmission:.56,ior:1.54,thickness:.006,attenuationColor:new THREE.Color(0xf47a16),attenuationDistance:.05,clearcoat:1,clearcoatRoughness:.07});}
function cabochon(name:string,rx:number,ry:number,rz:number,pear:boolean,m:THREE.Material){const g=new THREE.SphereGeometry(1,64,40);const p=g.attributes.position!;for(let i=0;i<p.count;i++){const y=p.getY(i),t=pear?(1-.36*y):1;p.setXYZ(i,p.getX(i)*rx*t,y*ry,p.getZ(i)*rz);}g.computeVertexNormals();return mesh(name,g,m);}
function emberInclusions(root:THREE.Group,rx:number,ry:number,rz:number){const m=new THREE.MeshStandardMaterial({name:'Suspended gold orange ember mineral feathers',color:0xf4a62c,metalness:.3,roughness:.36});for(let i=0;i<28;i++){const a=i*2.399963,y=Math.sin(i*3.17)*ry*.73,r=.25+.36*(.5+.5*Math.sin(i*1.73));const g=new THREE.TetrahedronGeometry(1);g.scale(rx*(.018+.016*(i%3)),ry*.03,rz*.006);g.rotateY(a);g.rotateZ(i*.73);g.translate(Math.cos(a)*rx*r,y,Math.sin(a)*rz*.45);root.add(mesh('Internal ember mineral flake '+i,g,m));}}
/** Five tapered, swept claws follow the domed stone instead of hovering as studs. */
function flameClaws(root:THREE.Group,rx:number,ry:number,_z:number,m:THREE.Material,pear:boolean){for(let k=0;k<5;k++){const a0=Math.PI/2+k/5*TAU,rz=pear?.0046:.0025,wide=pear?.00165:.0009;const p:number[]=[],uv:number[]=[],ix:number[]=[];const n=28,c=12;for(let i=0;i<=n;i++){const t=i/n,a=a0-.18+.31*t,r=1.045-.34*t,shape=pear?1-.36*Math.sin(a):1;const q=V(Math.cos(a)*rx*shape*r,Math.sin(a)*ry*r,rz*Math.sqrt(Math.max(0,1-r*r))+.00018);const tangent=V(-Math.sin(a),Math.cos(a),0),width=wide*Math.pow(1-t,.6)+.000025;for(let j=0;j<=c;j++){const b=j/c*TAU;const v=q.clone().addScaledVector(tangent,Math.cos(b)*width);v.z+=Math.sin(b)*(.00024+.00028*Math.sin(Math.PI*t))*Math.pow(1-t*.9,.5);p.push(v.x,v.y,v.z);uv.push(t,j/c);}}for(let i=0;i<n;i++)for(let j=0;j<c;j++){const a=i*(c+1)+j,b=a+c+1;ix.push(a,b,a+1,a+1,b,b+1);}for(let j=1;j<c-1;j++){ix.push(0,j+1,j);const e=n*(c+1);ix.push(e,e+j,e+j+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();root.add(mesh('Curved pointed silver flame claw '+k,g,m));}}
function emberPendant(root:THREE.Group){const silver=metal('Antique bright silver',0xb9bcc0,.3),gem=emberMaterial();const body=cabochon('Pear shaped fire amber cabochon',.0085,.014,.0046,true,gem);root.add(body);emberInclusions(root,.0085,.014,.0046);root.add(tube('Continuous pear silver bezel',Array.from({length:64},(_,i)=>{const a=i/64*TAU;return V(Math.cos(a)*.00865*(1-.36*Math.sin(a)),Math.sin(a)*.0141,0);}),.00078,silver,true));flameClaws(root,.0085,.014,.0021,silver,true);bail(root,silver);}
function emberRing(root:THREE.Group){const silver=metal('Engraved antique silver',0xb9bcc0,.3),gem=emberMaterial();root.add(band(.0035,.0017,'silver',silver));const setting=new THREE.Group();setting.name='Oval emberite flame crown';setting.rotation.x=-Math.PI/2;setting.position.y=.0122;setting.add(cabochon('Oval polished fire emberite',.0043,.0057,.0025,false,gem));emberInclusions(setting,.0043,.0057,.0025);setting.add(loop('Oval fitted silver bezel',0,0,0,.00445,.00585,.00052,silver));flameClaws(setting,.0043,.0057,.0007,silver,false);root.add(setting);for(const sign of[-1,1])for(const edge of[-1,1])root.add(tube('Raised silver split shoulder scroll', [V(sign*.011,.004,edge*.0016),V(sign*.009,.008,edge*.0023),V(sign*.006,.0118,edge*.0025),V(sign*.0038,.013,edge*.0022)],.0005,silver));}
function cinderRing(root:THREE.Group){const steel=metal('Hammered charcoal cindersteel',0x98918b,.43),copper=metal('Recessed hot copper seams',0xc66b3e,.31);root.add(band(.007,.002,'cinder',steel));for(const side of[-1,1]){const p:number[]=[],uv:number[]=[],ix:number[]=[];for(let i=0;i<=192;i++){const a=i/192*TAU;for(let j=0;j<=6;j++){const t=j/6*2-1,r=.01181+.0008*Math.pow(Math.max(0,Math.sin(a)),6)+.00005*(1-t*t),z=side*.00215+.00038*Math.sin(a*5+.7)+.00018*Math.sin(a*11)+t*.00036;p.push(r*Math.cos(a),r*Math.sin(a),z);uv.push(i/192*4,j/6);}}for(let i=0;i<192;i++)for(let j=0;j<6;j++){const a=i*7+j,b=a+7;ix.push(a,b,a+1,a+1,b,b+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();root.add(mesh('Recessed wandering copper ribbon '+side,g,copper));}}

const shield=[[-.012,.007],[-.006,.0105],[0,.014],[.006,.0105],[.012,.007],[.013,.001],[.007,-.011],[0,-.018],[-.007,-.011],[-.013,.001]].reverse();
function cinderPendant(root:THREE.Group){const steel=metal('Forged dark cindersteel shield',0x98918b,.43),copper=metal('Hammered copper channel inlay',0xca7148,.33);root.add(plaque('Thick angular shield body',shield,.0034,.0002,steel));const copperField=plaque('Recessed copper shield field',shield.map(p=>[p[0]!*.9,p[1]!*.9]),.001,.0001,copper);copperField.position.z=.0019;root.add(copperField);const panels=[[[0,.012],[.004,.008],[.0105,.006],[.006,.004],[.003,0],[0,-.008],[-.003,0],[-.006,.004],[-.0105,.006],[-.004,.008]], [[-.0098,.0035],[-.007,.001],[-.004,-.004],[-.001,-.014],[-.006,-.009],[-.010,-.001]], [[.0098,.0035],[.010,-.001],[.006,-.009],[.001,-.014],[.004,-.004],[.007,.001]]];panels.forEach((p,i)=>{const o=plaque('Raised steel shield plate '+i,p.reverse().map(q=>[q[0]!*.94,q[1]!*.96]),.0015,.0014,steel);o.position.z=.003;root.add(o);});bail(root,steel,copper);chain(root,steel);}
function nightMetal(){const m=metal('Blue black polished nightglass alloy',0x687fae,.3);m.map=texture('Nightglass cobalt hairline mineral veins',(x,y)=>{const f=Math.sin(x*20+Math.sin(y*11)*2)*Math.sin(y*17+Math.sin(x*14));const vein=Math.exp(-Math.abs(f)*45);return[130+vein*15,155+vein*40,195+vein*60];},true);m.emissive=new THREE.Color(0x386dff);m.emissiveIntensity=.2;m.emissiveMap=texture('Fine cobalt mineral vein response',(x,y)=>{const f=Math.sin(x*20+Math.sin(y*11)*2)*Math.sin(y*17+Math.sin(x*14));const v=Math.exp(-Math.abs(f)*65);return[255*v,255*v,255*v];},true);return m;}
function nightRing(root:THREE.Group){const dark=nightMetal(),rim=metal('Nightglass polished bevel edges',0x667898,.23);root.add(band(.007,.0017,'night',dark));for(let i=0;i<12;i++){const a=i/12*TAU;const p=plaque('Angular nightglass overlapping shank facet '+i,[[-.0028,-.0033],[.0018,-.0033],[.0028,0],[.0018,.0033],[-.0028,.0033]],.0004,.00022,dark);p.rotation.x=-Math.PI/2;p.rotation.z=-a+Math.PI/2;p.position.set(.0115*Math.cos(a),.0115*Math.sin(a),0);p.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(V(-Math.sin(a),Math.cos(a),0),V(0,0,1),V(Math.cos(a),Math.sin(a),0)));root.add(p);}const crown=plaque('Raised beveled lozenge signet',[[0,-.0044],[.0048,0],[0,.0044],[-.0048,0]],.0011,.0006,rim);crown.rotation.x=-Math.PI/2;crown.position.y=.0135;root.add(crown);const inset=plaque('Black blue lozenge crown face',[[0,-.0038],[.0041,0],[0,.0038],[-.0041,0]],.00035,.0002,dark);inset.rotation.x=-Math.PI/2;inset.position.y=.0142;root.add(inset);}
function nightPendant(root:THREE.Group){const dark=nightMetal(),rim=metal('Cold blue polished shield bevel',0x657791,.25);const outline=[[-.013,.006],[-.006,.010],[0,.014],[.006,.010],[.013,.006],[.010,.001],[.010,-.008],[0,-.018],[-.010,-.008],[-.010,.001]].reverse();root.add(plaque('Solid faceted nightglass shield body',outline,.004,.001,dark));const frame=plaque('Bright broad shield bevel',outline.map(p=>[p[0]!*.87,p[1]!*.87]),.002,.001,rim);frame.position.z=.002;root.add(frame);const inset=plaque('Ridged central blue black shield',outline.map(p=>[p[0]!*.77,p[1]!*.77]),.0015,.0010,dark);inset.position.z=.0029;root.add(inset);bail(root,dark);chain(root,dark);}
const descriptions:Record<string,string>={emberite_ring:'Silver split scroll shoulders, swept flame claws and translucent oval orange fire amber cabochon; circular 20 mm comfort bore.',emberite_pendant:'Pear fire amber cabochon in continuous silver bezel with five sculpted flame claws, articulated jump ring and open bail.',cindersteel_ring:'Broad charcoal hammered band with two wandering recessed copper seams and smooth 20 mm comfort bore.',cindersteel_pendant:'Thick pointed shield with separately raised ridged steel plates, exposed branching copper channels and copper striped bail with articulated chain.',nightglass_ring:'Blue black angular overlapping facets around a comfort bore with elevated beveled lozenge signet.',nightglass_pendant:'Solid blue black ridged shield with broad polished angular bevel, tapered open bail and articulated dark chain.'};
export const author:ItemModelAuthor={ids:Object.keys(descriptions),build(itemId){if(!descriptions[itemId])throw new Error('Unsupported jewelry '+itemId);const root=new THREE.Group();root.name=itemId.replaceAll('_',' ');root.userData.itemModel={itemId,author:'jewelry-metal-b',reference:'art/item-icons/generated/'+itemId+'.png',description:descriptions[itemId]};const builders:Record<string,(g:THREE.Group)=>void>={emberite_ring:emberRing,emberite_pendant:emberPendant,cindersteel_ring:cinderRing,cindersteel_pendant:cinderPendant,nightglass_ring:nightRing,nightglass_pendant:nightPendant};builders[itemId]!(root);return root;}};
