import assert from "node:assert/strict";
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { chromium, type Page } from "playwright";
import { createServer } from "vite";
import { repoRoot } from "./lib/paths.js";
import type { ViewerSnapshot } from "../devdocs/src/viewer/types.js";

const evidence = path.join(repoRoot, "test-results/devdocs");
await mkdir(evidence, { recursive: true });
const temporary = await mkdtemp(path.join(tmpdir(), "corealm-devdocs-smoke-"));
const contentRoot = path.join(temporary, "content");
await cp(path.join(repoRoot, "game/content/data"), path.join(contentRoot, "data"), { recursive: true });
const oldRoot = process.env.DEVDOCS_CONTENT_ROOT;
process.env.DEVDOCS_CONTENT_ROOT = contentRoot;
const server = await createServer({ configFile: path.join(repoRoot, "devdocs/vite.config.ts"), cacheDir: path.join(repoRoot, "node_modules/.vite-devdocs-smoke"), optimizeDeps: { force: true }, logLevel: "error", server: { host: "127.0.0.1", port: 0, strictPort: false, hmr: false } });
if (oldRoot === undefined) delete process.env.DEVDOCS_CONTENT_ROOT; else process.env.DEVDOCS_CONTENT_ROOT = oldRoot;
const browser = await chromium.launch({ headless: true });
const errors: string[] = [];
const checks: Record<string, unknown> = {};
let expectedConflict = false;
async function snapshot(page: Page): Promise<ViewerSnapshot> { return JSON.parse((await page.locator("script[data-viewer-state]").textContent())!) as ViewerSnapshot; }
async function moving(page: Page): Promise<ViewerSnapshot> {
  await page.locator('[data-viewer-ready="true"]').waitFor({ timeout: 50_000 });
  const before = await snapshot(page);
  await page.waitForFunction(time => {
    const state = JSON.parse(document.querySelector("script[data-viewer-state]")!.textContent!);
    return state.time !== time;
  }, before.time);
  const after = await snapshot(page);
  assert(after.playing && after.clips.length > 0);
  return after;
}
try {
  await server.listen();
  const address = server.httpServer!.address();
  if (!address || typeof address === "string") throw new Error("Missing TCP address");
  const url = `http://127.0.0.1:${address.port}`;
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, colorScheme: "dark" });
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (message.type() === "error" && !(expectedConflict && message.text().includes("409"))) errors.push(message.text()); });
  page.on("response", response => { if (response.status() >= 400 && !(expectedConflict && response.status() === 409)) errors.push(`${response.status()} ${response.url()}`); });
  await page.goto(`${url}/#/items`);
  await page.getByRole("grid", { name: "Items", exact: true }).waitFor();
  assert(await page.getByRole("row").count() < 100, "Item table must virtualize 399 records");
  checks.virtualizedItems = true;
  await page.screenshot({ path: path.join(evidence, "items-dark.png") });
  await page.getByRole("textbox", { name: "Search items", exact: true }).fill("grithe_sword");
  await page.getByRole("row").filter({ hasText: "Copper Sword" }).click();
  await page.getByRole("heading", { name: "Copper Sword", exact: true }).waitFor();
  await page.waitForFunction(() => (document.querySelector(".item-art-large img") as HTMLImageElement)?.naturalWidth === 256);
  checks.itemMasterIcon = 256;
  await page.getByRole("tab", { name: "Sources and uses", exact: true }).click();
  await page.getByRole("button", { name: "Copper Sword", exact: true }).waitFor();
  checks.itemRecipeConnection = true;
  await page.getByRole("tab", { name: "3D model", exact: true }).click();
  const sword = await moving(page);
  assert(sword.clip?.includes("Sword_Attack"));
  assert(sword.attachments.some(part => part.slot === "mainHand" && part.bone));
  checks.sword = { clip: sword.clip, attachments: sword.attachments, time: sword.time };
  await page.screenshot({ path: path.join(evidence, "sword.png") });
  await page.goto(`${url}/#/equipmentSets/hide`);
  await page.getByRole("tab", { name: "3D model", exact: true }).click();
  await moving(page);
  await page.getByLabel("Body", { exact: true }).selectOption("female");
  await page.waitForFunction(() => document.querySelector('[data-viewer-body="female"]')?.getAttribute("data-viewer-ready") === "true");
  const female = await moving(page);
  assert(female.parts.length >= 5 && female.missingBones.length === 0);
  checks.femaleSet = { parts: female.parts, clip: female.clip, missingBones: female.missingBones };
  await page.getByRole("button", { name: "Pause", exact: true }).click();
  const paused = await snapshot(page);
  await page.getByLabel("Animation time", { exact: true }).fill(String(paused.duration / 2));
  const scrubbed = await snapshot(page);
  assert(!scrubbed.playing && Math.abs(scrubbed.time - paused.duration / 2) < .02);
  await page.screenshot({ path: path.join(evidence, "female-set.png") });
  await page.keyboard.press("Control+k");
  await page.getByRole("dialog").waitFor();
  await page.getByRole("combobox").fill("redbrush_fox");
  await page.getByRole("option").filter({ hasText: "Creatures" }).first().click();
  await page.getByRole("tab", { name: "3D model", exact: true }).click();
  const creature = await moving(page);
  checks.creature = { clip: creature.clip, clips: creature.clips.length, time: creature.time };
  await page.screenshot({ path: path.join(evidence, "creature.png") });
  await page.getByRole("button", { name: "Switch to light theme" }).click();
  assert.equal(await page.locator("html").getAttribute("data-theme"), "light");
  await page.goto(`${url}/#/items`);
  await page.getByRole("grid", { name: "Items", exact: true }).waitFor();
  await page.screenshot({ path: path.join(evidence, "items-light.png") });
  await page.getByLabel("Group by", { exact: true }).selectOption("");
  const grid = page.getByRole("grid", { name: "Items", exact: true });
  await grid.focus(); await page.keyboard.press("End"); await page.keyboard.press("Enter");
  await page.getByRole("tab", { name: "Overview", exact: true }).waitFor();
  checks.keyboardNavigation = true;
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Open navigation" }).click();
  await page.locator(".sidebar").getByRole("button", { name: /^gear \d+$/ }).click();
  await page.waitForFunction(() => location.hash.includes("balance"));
  await page.getByRole("grid", { name: "gear", exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 390);
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector(".page-transition")!).opacity) >= .99);
  await page.screenshot({ path: path.join(evidence, "mobile-balance.png") });
  checks.mobileWidth = 390;
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.goto(`${url}/#/items/grithe_sword`);
  await page.getByRole("tab", { name: "Edit", exact: true }).click();
  const description = page.getByRole("textbox", { name: "Description", exact: true });
  await description.fill("A copper sword edited by the isolated browser smoke.");
  await page.getByRole("tab", { name: "Overview", exact: true }).click();
  await page.getByRole("tab", { name: "Edit", exact: true }).click();
  assert.equal(await description.inputValue(), "A copper sword edited by the isolated browser smoke.");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await page.getByText("Changes saved", { exact: true }).waitFor();
  const itemFile = path.join(contentRoot, "data/items.json");
  const savedItems = JSON.parse(await readFile(itemFile, "utf8")) as { id: string; description: string }[];
  assert.equal(savedItems.find(row => row.id === "grithe_sword")!.description, "A copper sword edited by the isolated browser smoke.");
  checks.isolatedItemEdit = true;
  await description.fill("A draft that must survive a conflict.");
  const current = await (await page.request.get(`${url}/__devdocs/collections/items`)).json();
  const copper = current.data.find((row: { id: string }) => row.id === "grithe_sword");
  const concurrent = await page.request.put(`${url}/__devdocs/collections/items/grithe_sword`, { data: { revision: current.revision, record: { ...copper, description: "A concurrent author saved this text." } } });
  assert.equal(concurrent.status(), 200);
  expectedConflict = true;
  const conflictResponse = page.waitForResponse(response => response.status() === 409);
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await conflictResponse;
  await page.getByText(/This file changed after you opened it/).waitFor();
  assert.equal(await description.inputValue(), "A draft that must survive a conflict.");
  assert(await page.getByRole("button", { name: "Save changes", exact: true }).isDisabled());
  assert.equal((JSON.parse(await readFile(itemFile, "utf8")) as typeof savedItems).find(row => row.id === "grithe_sword")!.description, "A concurrent author saved this text.");
  await page.screenshot({ path: path.join(evidence, "edit-conflict.png") });
  await page.getByRole("button", { name: "Reset draft", exact: true }).click();
  await page.waitForFunction(() => (document.querySelector('textarea[aria-label="Description"]') as HTMLTextAreaElement)?.value === "A concurrent author saved this text.");
  expectedConflict = false;
  checks.conflictPreservesDraft = true;
  await page.getByRole("tab", { name: "Notes", exact: true }).click();
  await page.getByRole("checkbox", { name: "Flag as request", exact: true }).check();
  await page.getByPlaceholder("Describe the change to make").fill("Review this sword's grip from the browser.");
  await page.getByRole("tab", { name: "Overview", exact: true }).click();
  await page.getByRole("tab", { name: "Notes", exact: true }).click();
  assert.equal(await page.getByPlaceholder("Describe the change to make").inputValue(), "Review this sword's grip from the browser.");
  checks.draftsSurviveTabs = true;
  await page.getByLabel("Request kind", { exact: true }).selectOption("art");
  await page.getByRole("button", { name: "Open request", exact: true }).click();
  await page.locator(".notes-entry-text").filter({ hasText: "Review this sword's grip from the browser." }).waitFor();
  await page.screenshot({ path: path.join(evidence, "notes-request.png") });
  checks.browserRequestWrite = true;
  await page.goto(`${url}/#/requests`);
  await page.getByRole("heading", { name: "Requests", exact: true }).waitFor();
  await page.getByText("Review this sword's grip from the browser.", { exact: true }).waitFor();
  checks.requestsPage = true;
  await page.goto(`${url}/#/kits`);
  await page.getByRole("group", { name: "Filter by tier", exact: true }).getByRole("button", { name: "1", exact: true }).click();
  assert.equal(await page.locator(".kits-tier").count(), 1);
  await page.getByRole("button", { name: "Open Copper Sword", exact: true }).waitFor();
  await page.keyboard.press("/");
  assert(await page.getByRole("textbox", { name: "Search kits", exact: true }).evaluate(element => element === document.activeElement));
  await page.screenshot({ path: path.join(evidence, "kits.png") });
  await page.getByRole("button", { name: "Open Copper Sword", exact: true }).click();
  await page.getByRole("heading", { name: "Copper Sword", exact: true }).waitFor();
  checks.kits = true;
  await page.goto(`${url}/#/balance/gear/rare`);
  await page.getByRole("tab", { name: "Edit", exact: true }).click();
  const rareMultiplier = page.locator('[id="edit-rare.bonusMultiplier"] input');
  await rareMultiplier.fill("1.25");
  const itemsBeforeParameterEdit = await readFile(itemFile, "utf8");
  const parameterSaved = page.waitForResponse(response => response.request().method() === "PUT" && response.url().includes("balance"));
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  assert.equal((await parameterSaved).status(), 200);
  assert.equal(await readFile(itemFile, "utf8"), itemsBeforeParameterEdit, "Parameter saves must not silently rewrite items");
  const driftValidation = await (await page.request.post(`${url}/__devdocs/validate`)).json();
  assert.equal(driftValidation.ok, false);
  assert(driftValidation.diagnostics.some((issue: { message: string; severity: string }) => issue.severity === "error" && issue.message.includes("Drifted")));
  await page.getByRole("tab", { name: "Formula", exact: true }).click();
  await page.locator(".balance-code .shiki").waitFor();
  await page.getByRole("button", { name: "Preview changes", exact: true }).click();
  await page.getByRole("button", { name: "Apply changes to 8 records", exact: true }).waitFor();
  assert.equal(await readFile(itemFile, "utf8"), itemsBeforeParameterEdit, "Preview must not write");
  await page.screenshot({ path: path.join(evidence, "balance-preview.png") });
  await page.getByRole("button", { name: "Apply changes to 8 records", exact: true }).click();
  await page.getByText(/Applied changes to 8 records/).waitFor();
  assert.notEqual(await readFile(itemFile, "utf8"), itemsBeforeParameterEdit);
  const recomputed = await (await page.request.post(`${url}/__devdocs/recompute`, { data: { operation: "preview", kind: "gear" } })).json();
  assert.deepEqual(recomputed.diffs, []);
  const validation = await (await page.request.post(`${url}/__devdocs/validate`)).json();
  assert.equal(validation.ok, true, JSON.stringify(validation.diagnostics));
  const gitStatus = await (await page.request.get(`${url}/__devdocs/git/status`)).json();
  assert(Array.isArray(gitStatus.changes));
  checks.parameterPreviewApply = { count: 8, remaining: 0 };
  const metadataUrl = `${url}/__devdocs/meta/items/grithe_sword`;
  const metadata = await (await page.request.get(metadataUrl)).json();
  const written = await page.request.patch(metadataUrl, { data: { revision: metadata.revision, operation: { kind: "request.open", requestId: "smoke-grip", requestKind: "art", text: "Verify the grip." } } });
  assert.equal(written.status(), 200);
  const report = await (await page.request.get(`${url}/__devdocs/requests`)).json();
  assert(report.requests.some((row: { entityId: string }) => row.entityId === "grithe_sword"));
  assert((await readFile(path.join(contentRoot, "meta/items.meta.json"), "utf8")).includes("smoke-grip"));
  checks.isolatedRequestWrite = true;
  assert.deepEqual(errors, []);
  await writeFile(path.join(evidence, "report.json"), JSON.stringify({ passed: true, checks, errors }, null, 2));
  console.log(JSON.stringify({ passed: true, checks, errors }, null, 2));
} catch (error) {
  await writeFile(path.join(evidence, "report.json"), JSON.stringify({ passed: false, checks, errors, error: String(error) }, null, 2));
  throw error;
} finally {
  await browser.close(); await server.close();
  if (path.dirname(temporary) !== path.resolve(tmpdir())) throw new Error("Unexpected temporary root");
  await rm(temporary, { recursive: true, force: true });
}
