/** Root-only promotion after actual production-lab browser acceptance. */
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '../..');
const evidenceArg = process.argv[process.argv.indexOf('--evidence') + 1];
assert(process.argv.includes('--evidence') && evidenceArg, 'Provide --evidence <passing-report.json>');
const read = p => readFile(path.resolve(root, p));
const json = async p => JSON.parse(await read(p));
const hash = b => createHash('sha256').update(b).digest('hex');
const tail = b => b.subarray(20 + b.readUInt32LE(12));
const evidence = await json(evidenceArg);
assert.equal(evidence.passed, true);
const accepted = evidence.acceptedCandidateIds ?? evidence.candidateIds ?? evidence.catalogIds;
assert(accepted?.includes('crownward_timber_bridge'), 'Report must explicitly accept crownward_timber_bridge');
const catalog = await json('tools/crownward-bridges/catalog.json');
const provenance = await json('tools/crownward-bridges/provenance.json');
assert.equal(catalog.assets.length, 1); assert.equal(catalog.packs.length, 1);
const asset = catalog.assets[0], pack = catalog.packs[0];
assert.equal(asset.id, 'crownward_timber_bridge');
assert.equal(asset.file, 'models/crownward-bridges/crownward_timber_bridge.glb');
assert.equal(pack.license, 'CC0-1.0'); assert.deepEqual(pack, provenance.pack);
assert.equal(hash(await read('tools/crownward-bridges/build.mjs')), catalog.generator.generatorSha256);
const source = await read(pack.sourcePath), staged = await read(`test-results/crownward-bridges/${asset.file}`);
assert.equal(hash(source), pack.archiveSha256); assert.equal(source.length, 72792);
assert.equal(hash(staged), asset.sha256); assert.equal(staged.length, asset.bytes);
assert.equal(hash(tail(source)), provenance.sourceBinSha256);
assert.equal(hash(tail(staged)), provenance.candidateBinSha256);
assert.equal(provenance.sourceBinSha256, provenance.candidateBinSha256);
const manifest = await json('game/public/assets/manifest.json');
asset.acceptance = { ...asset.acceptance, labAccepted: true, worldIntegrated: process.argv.includes('--integrated'), evidence: path.relative(root, path.resolve(root, evidenceArg)).replaceAll('\\', '/') };
const assetIndex = manifest.assets.findIndex(a => a.id === asset.id);
if (assetIndex < 0) manifest.assets.push(asset); else manifest.assets[assetIndex] = asset;
const packIndex = manifest.packs.findIndex(p => p.id === pack.id);
if (packIndex < 0) manifest.packs.push(pack); else manifest.packs[packIndex] = pack;
await mkdir(path.resolve(root, 'game/public/assets/models/crownward-bridges'), { recursive: true });
await writeFile(path.resolve(root, 'game/public/assets', asset.file), staged);
await writeFile(path.resolve(root, 'game/public/assets/manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
console.log(JSON.stringify({ promoted: asset.id, evidence: asset.acceptance.evidence }));
