import {
  Axe, BookOpen, Boxes, Bug, ClipboardList, Flame, FlaskConical, Gem, Hammer, Layers, Leaf, Map as MapIcon, MapPin, MessageCircle,
  Mountain, Music2, PawPrint, Route, ScrollText, Shield, Shirt, SlidersHorizontal, Sparkles, Store, Swords, TreePine, Users, Wand2,
  Workflow, type LucideIcon,
} from "lucide-react";
import { collectionName } from "../model/rows.js";

/* Labels and icons per collection. Navigation itself lives in ui/workspaces.ts. */
const labels: Record<string, string> = {
  items: "Items",
  "compiled-items": "Items",
  "compiled-recipes": "Recipes",
  recipes: "Recipes",
  "compiled-resources": "Resources",
  resources: "Resources",
  "compiled-enemies": "Enemy stats",
  "compiled-species": "Species",
  equipmentSets: "Armour sets",
  sets: "Armour sets",
  campfireFuels: "Campfire fuels",
  kits: "Kit ladder",
  progression: "Tiers",
  materials: "Materials",
  equipmentFamilies: "Equipment families",
  recipeTemplates: "Recipe templates",
  creatureDefinitions: "Creatures",
  creatureProfiles: "Combat profiles",
  lootTables: "Loot tables",
  world: "World map",
  worldRegions: "Regions",
  encounters: "Encounters",
  placements: "Placements",
  resourcePlacements: "Resource nodes",
  npcs: "NPCs",
  shops: "Shops",
  quests: "Quests",
  dialogue: "Dialogue",
  spells: "Spells",
  spellRunes: "Runes",
  elementalSpells: "Elemental spells",
  assets: "Models",
  audio: "Audio",
  formulas: "Formulas",
  "balance/recipes": "Recipe balance",
  "balance/sets": "Set balance",
  "balance/campfires": "Campfire balance",
  "balance/formation": "Formation balance",
  "work-queue": "Work queue",
  requests: "Requests",
  review: "Review",
};

const icons: Record<string, LucideIcon> = {
  items: Swords,
  "compiled-items": Swords,
  "compiled-recipes": Hammer,
  recipes: Hammer,
  "compiled-resources": Leaf,
  resources: Leaf,
  "compiled-enemies": Bug,
  "compiled-species": PawPrint,
  equipmentSets: Shirt,
  sets: Shirt,
  campfireFuels: Flame,
  kits: Layers,
  progression: Workflow,
  materials: Gem,
  equipmentFamilies: Shield,
  recipeTemplates: Hammer,
  creatureDefinitions: PawPrint,
  creatureProfiles: Swords,
  lootTables: Boxes,
  world: MapIcon,
  worldRegions: Mountain,
  encounters: Route,
  placements: MapPin,
  resourcePlacements: TreePine,
  npcs: Users,
  shops: Store,
  quests: ScrollText,
  dialogue: MessageCircle,
  spells: Wand2,
  spellRunes: Gem,
  elementalSpells: FlaskConical,
  assets: Boxes,
  audio: Music2,
  formulas: SlidersHorizontal,
  "work-queue": ClipboardList,
  requests: ClipboardList,
  review: ClipboardList,
  home: BookOpen,
  tools: Axe,
};

export const labelFor = (name: string): string => labels[name] ?? collectionName(name).replace(/^Balance Â· /, "Balance / ");
export const iconFor = (name: string): LucideIcon => name.startsWith("balance/") ? SlidersHorizontal : icons[name] ?? Boxes;
export const isGeneratedCollection = (name: string): boolean => name.startsWith("compiled-");
